### ISSUE TITLE
Unable to determine channel name when subscribing with wildcard.

### ISSUE THREAD

**Issue by ps2** [faye/faye#119]
If I subscribe to /games/\* and a message is published to /games/x, the callback does not have any way of figuring out the actual channel name ('x') that the message was published to.

An obvious workaround is to modify the message to include the channel name, but it seems a fairly common case that someone subscribing with a wildcard would need the channel name.

**Comment by carter-thaxton** [comment]
Before checking here, I just tried the second argument, assuming "of course they'll provide that info as an additional argument".  No such luck.  Please just add the channel name as a second argument.  It won't break the API, and will be useful for everyone.  Thank you.

**Comment by justcfx2u** [comment]
To be at risk of beating a long-dead horse, @carter-thaxton's patch looks like an elegant solution.
