### ISSUE TITLE
Faye hangs and doesn't accept new connections with ~1000 clients.

### ISSUE THREAD

**Issue by zharikovpro** [faye/faye#156]
I wrote simple benchmark for Faye and found out weird error.

When stress test is running and has reached 401 errors, Faye server doesn't respond to any connections at all (even to /faye.js) and doesn't publish messages. That test came from real life app... I want to send notices to all subscribed users about new user's arrival. Even if you put timeouts and, for example, connect 1000+ clients per hour it would still produce same error (that's how I found it - got this situation twice).

Please take a look at this simple source code with comments:

https://gist.github.com/3190469#comments

A) 10000 connections - FINE

node server-connections.node.js &
node stress.node.js 10000

Runs fast and successful

B) 2000 connections and publish - BUG?

node server-publish.node.js &
node stress.node.js 2000

Runs ~10 times slower and around 1100 connections produces:

CONNECTED! 1096
CONNECTED! 1099
CONNECTED! 1095
401:17q44ad061fq9g1g1aplr0gauwph:Unknown client
401:0hu750o1mkvfyg0fbmh5n1rfou8f:Unknown client
401:1ksji9f0xg9r621cqlc0g0622e7y:Unknown client

I'm using Faye 0.8.3 and Node 0.6.8 (will also try it with Node 0.8.4)

What's wrong, how can I handle it?

**Comment by prathapc** [comment]
That's a quick fix @lifecoding. What if each milli sec is crucial for me and all my 1lac or 10lac users need to get instant notifications. Does faye going to handle this load, if not do you have any alternate solution?

**Comment by lifecoding** [comment]
It depends on your hardware I think. Dont tried it, but redis storage
backend and horizontal scaling can help.

2015-05-03 11:07 GMT+03:00 Prathap chowdary <notifications@github.com>:

> That's a quick fix @lifecoding <https://github.com/lifecoding>. What if
> each milli sec is crucial for me and all my 1lac or 10lac users need to get
> instant notifications. Does faye going to handle this load, if not do you
> have any alternate solution?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/faye/faye/issues/156#issuecomment-98453378>.
>



-- 
С уважением,
Андрей Жариков
http://lifecoder.ru

**Comment by fatso83** [comment]
@zharikovpro : Just a little notice from myself: your eight core server does not matter. Node only runs on one core. If you want to reach 800% cpu you need to spin up 8 Node modules. IISNode does this, for instance. There are similar tools on *nix.

**Comment by zharikovpro** [comment]
Yes, should be just fine with redis as storage engine.
