### ISSUE TITLE
Service channels

### ISSUE THREAD

**Issue by pselden** [faye/faye#172]
I just wanted to get some feelers out there onne possible implementation of service channels. I'm not even sure I'm using them how I'm supposed to be, but wanted to try something out to see if it would fall in line with what you had in mind.

https://github.com/pselden4/faye/commit/a8725609f32e96ff5b45e1063198484d3c868a68
In this implemenation, the service would be completely instrumented through the use of extensions. You'd attach data to ext and an outgoing server side extension would handle calling the proper service with the credentials you supplied for the user. An incoming server side extension would be responsible for validating the user's credentials.

A client side extension would attach the credentials.

Here's how it might be used:

``` javascript
  // client
  client.addExtension({
    outgoing: function(message, callback){
      if(!Faye.Channel.isService(message.channel)){
        return callback(message);
      }

       // stuff that adds a token that will be used to verify userId
       callback(message);
   });

  client.service('myservice', { userId: 1}, function(response) {
     console.log(response);
  });

  // server
  server.addExtension({
    incoming: function(message, callback) {
       // something to validate the userId
    },
    outgoing: function(message, callback) {
      if(message.service !== 'myservice') {
         return callback(message);
      }

      myService(message.serviceData.userId, function(err, result){
        if(err) {
           message.error = err; 
        } else {
           message.result = result;
        }

        callback(message);
      });
    }
```

Could you give me your thoughts about this? The bayeux spec says something about how service channels are implementation specific, but what are your thoughts about relying on extensions heavily for this?

**Comment by thesmart** [comment]
I needed /service/** support so I added a request method to the faye client:
https://github.com/faye/faye/issues/172
