### ISSUE TITLE
Correct HAProxy config to prevent "Received request with no message" error

### ISSUE THREAD

**Issue by zakjan** [faye/faye#239]
I run my own server with HAProxy loadbalancer on port 80 distributing to multiple Faye servers on ports 9201-9210 and I see many errors like this in log.

[ERROR] [Faye::RackAdapter] Received request with no message: "curl -X GET 'http://domain.tld/ws'"
[ERROR] [Faye::RackAdapter] Received request with no message: "curl -X GET 'http://domain.tld/ws?someParam=value'"
And rarely even:
[ERROR] [Faye::RackAdapter] Received request with no message: "curl -X POST 'http://domain.tld/ws?someParam=value' -H 'Content-Type: ' -d ''"

My HAProxy 1.4 relevant config:

```
defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        retries 3
        # option redispatch # disabled because sticky to server
        maxconn 10000
        timeout client 5s
        timeout connect 5s
        timeout server 5s

frontend all :80
        mode http
        option forwardfor
        option http-server-close
        option http-pretend-keepalive
        timeout client 120s

        acl path_match path_beg -i /ws

        use_backend faye if path_match
        default_backend www

backend www
        server www1 localhost:8080

backend faye
        timeout server 120s

        balance url_param someParam
        hash-type consistent # because of sticky to server

        option httpchk /ws

        server faye1  localhost:9201 check
        server faye2  localhost:9202 check
        server faye3  localhost:9203 check
```

I need to route to particular server based on someParam GET value, so I always use 'http://domain.tld/ws?someParam=value' URL to connect to Faye. It is strange why sometimes is this GET parameter missing. Or why there is POST request with no body.

I don't want to disable WebSocket connection method as suggested above, application is working fine from user's view. Maybe only sometimes connection fails and on next try is successful, so users experience only small lag in application, which they don't report to our support.

Can you help me check HAProxy config, if something can be cause for these errors?

**Comment by rahulbca18** [comment]
I am facing a issue with haproxy firest request is success and second or may be third will 404. My log files are
Nov 20 23:20:28 localhost haproxy[71081]: 127.0.0.1:34370 [20/Nov/2018:23:20:28.657] EAP vahan_tax_bck/vahan_ser8 0/0/0/89/89 200 1152 - - ---- 4/4/0/1/0 0/0 "POST /vahantaxws/vahantax HTTP/1.1"

Nov 20 23:20:40 localhost haproxy[71081]: 127.0.0.1:34600 [20/Nov/2018:23:20:40.878] EAP vahan_tax_bck/vahan_ser85 0/0/0/3/3 404 1180 - - ---- 3/3/0/1/0 0/0 "GET /vahantaxws/vahantax?wsdl HTTP/1.1"

I am using roundrobin algo for Load balancing 

please see help will very appreciated ..
