### ISSUE TITLE
Using Faye with SSL enabled site

### ISSUE THREAD

**Issue by OlegLazaryev** [faye/faye#241]
Hi!

I am using Faye with Thin server in my project, which works over https.
This is Rails app which works with Nginx and Passenger.

I configured my Faye to work on http://localhost:9292/faye but my client is doing requsts on https://my.domain.com/faye (because I can`t do request on http://localhost:9292 due to unsafe connection) and Nginx is proxying all requests which come on "/faye" to "http://localhost:9292/faye". When I am publishing nottification on the server I am making request directly to http://localhost:9292/faye.

So, the problem is that when I am doing nottification from the server I must wait for it on the client side near 30-50 seconds. What should I do to solve this issue? Is the problem in my nginx proxy configuration or should I configure faye and thin to work with ssl instead of http?

Also I found part of code in faye.js which is changing part of url from https(when it is detected) to wss. Am I right that when client works over https it can only do websocket requests and can't do http?

I can provide code of my configurations if it is required.
Also it would be great to have some manual where I can find some steps for configuring faye to work properly with https site.
I am looking forward for your feedback.

**Comment by ikaiser** [comment]
I have this

faye.ru :

require 'faye'
Faye::WebSocket.load_adapter('thin')
faye_server = Faye::RackAdapter.new(:mount => '/faye', :timeout => 45)
run faye_server

and i lunch faye server with this command:

RAILS_ENV=production rackup faye.ru -s thin -E anzio --host 0.0.0.0 -D

but when i try this address in chrome or other browser i get 500 error
https://www.sitename.com:8001/faye.js OR https://www.sitename.com:8001/faye/client.js

why ?? where is the bug??
thanks.

**Comment by jcoglan** [comment]
@ikaiser There's nothing in your configuration to enable SSL for your Thin server. Are you accessing the Thin server via a proxy that terminates SSL? If not, you should look up Thin's options for turning on SSL, providing a certificate and so on -- try `thin --help` for more information.
