### ISSUE TITLE
register faye-browser.js as Bower package

### ISSUE THREAD

**Issue by elf-pavlik** [faye/faye#242]
"Bower is a package manager for the web. It offers a generic, unopinionated solution to the problem of front-end package management, while exposing the package dependency model via an API that can be consumed by a more opinionated build stack. There are no system wide dependencies, no dependencies are shared between different apps, and the dependency tree is flat.

Bower runs over Git, and is package-agnostic. A packaged component can be made up of any type of asset, and use any type of transport (e.g., AMD, CommonJS, etc.)."

http://bower.io/#registering-packages

since this repository currently doesn't include built version in may need some fiddling, relevant discussion in Leaflet/Leaflet#1903 mentionoing bower/bower#455

**Comment by Light241** [comment]
I'm also add repo for bower distribution
https://github.com/Light241/faye-client

`bower install faye-client --save`

Just because [faye-browser][1] didn't accept pull request with latest versions

[1]: https://github.com/hackers4peace/faye-browser

**Comment by elf-pavlik** [comment]
thanks @Light241 and my bad with missing that PR!
if you like please request changing faye in bower to your repository

**Comment by Light241** [comment]
@elf-pavlik I think that's not necesary. 
By the way somebody may need older versions of faye for some reasons. Let's keep them in your repo
