### ISSUE TITLE
When Faye client's network connection is dropped, messages are buffered, but not all of them get delivered to the client after reconnect.

### ISSUE THREAD

**Issue by ttomor** [faye/faye#251]
If a Faye client's network connection is dropped, messages are buffered, but the client does not receive all of them when he gets back 'online'. I don't know if this is normal behaviour or not. I've provided some code and steps for reproducing this "bug" [here](https://github.com/ttomor/faye-lost-messages)

**Comment by davidmoshal** [comment]
just curious what the status of this is?
specifically, is there a way for clients to reconnect and get any missed messages?

**Comment by jcoglan** [comment]
@davidmoshal if a client becomes disconnected for significantly longer than the server's `timeout` setting, then its session will be destroyed and any messages it missed will be lost. If it reconnects before its session is deleted it should still receive everything.
