### ISSUE TITLE
Event handler dies after first transmission

### ISSUE THREAD

**Issue by ozpozner** [faye/faye#310]
Thanks for a great work,
I am a rails newbie After a long "research" on EM not initialized i came up with 

module Bayeux
  def self.client
    @client ||= begin
      Thread.new { EM.run } unless EM.reactor_running?
      Thread.pass until EM.reactor_running?
      Faye::Client.new('http://localhost:9292/faye')
    end
  end

 and now it dies after the first message
I saw your wrapper

 class FayeWrapper
  def self.publish(channel, message)
    run_event_machine
    $faye.publish(channel, message)
  end

  def self.run_event_machine
    Thread.new { EM.run } unless EM.reactor_running?
    Thread.pass until EM.reactor_running?
  end
end

which should fix this EM hanging where should i place this in /config/initializers/faye.rb ? faye.ru ?
can you please refer me to a full example ?
thanks in advance,

**Comment by habitullence** [comment]
@jcoglan I've just run into a similar problem. Can you give me some pointers on how to investigate why Event Machine's dying?

**Comment by habitullence** [comment]
It's dying with Cucumber - seems to be available in first but not subsequent steps.

**Comment by johnnieshlomo** [comment]
> If EventMachine is being killed after you create a Faye client, then that client will not work correctly.
Hi, I am facing the exact same issue. I'm using Faye with eventmachine like so:
`EM.run do
      client = Faye::Client.new(@faye_url)
      puts "connected"
      publication = client.publish("/" + token, "result" => response(payment))
      publication.callback do
        puts "SUCCESS!"
        client.disconnect
        EM.stop_event_loop
      end
      publication.errback do |_error|
        puts "[PUBLISH FAILED]"
      end
    end`

did you find a way to solve this issue?

**Comment by jcoglan** [comment]
@johnnieshlomo it looks like you're stoping EventMachine yourself inside the `publish` callback, which will definitely break the client.
