### ISSUE TITLE
Invalid gemspec when installing from git

### ISSUE THREAD

**Issue by Intrepidd** [faye/faye#316]
Hello,

When installing from git, rubygems complains with the following message :

```
faye at /Users/adrien/xxxxx/vendor/cache/faye-590a5f6f4860 did not have a valid gemspec.
This prevents bundler from installing bins or native extensions, but that may not affect its functionality.
The validation message from Rubygems was:
  ["lib/faye-browser-min.js", "lib/faye-browser-min.js.map", "lib/faye-browser.js"] are not files
```

Obviously because the generated js and map files are not checked in into git.

A quick fix would be to check them into git but you may have another opinion on that

Thanks !

**Comment by asmatameem** [comment]
I am getting the same error. Can you please provide more details on how to fix this?

**Comment by jcoglan** [comment]
@asmatameem The Ruby gem contains JS that needs to be bundled/minified from the source code. Instructions for this are in https://github.com/faye/faye/blob/master/CONTRIBUTING.md, specifically you need to run:

```
npm install
npm run build
```
