### ISSUE TITLE
Initialize Faye Clients with a specific client Id

### ISSUE THREAD

**Issue by Intrepidd** [faye/faye#321]
Imagine a Faye Ruby / Node client being connected permanently to a Faye Server, receiving tons of events.

Sometimes you have to restart that client because you're releasing new code.

The problem is, some events will be lost during the restart phase.

It would be neat to have the two following features :
- An event triggered on the client when the handshake is successful, with the clientId, allowing the user to store this clientId somewhere.

``` ruby
client.on(:handshake_successful) do |clientId|
  # Do amazing stuff with clientId
end
```
- The ability to provide the clientId at the client initialization. This would set the client directly in a connected state, and we'll receive messages being queued in the server.

``` ruby
client = Faye::Client.new('http://faye.server/faye', clientId: 'hzyifnug5pg8i4vjbtqqnuhyf3zh9fw')
```

What do you think ? Do you have any other solution to this problem ? 

Thanks ! :+1:

**Comment by Xsmael** [comment]
@Intrepidd Have you made that extension ? i think i'll need something similar...
