### ISSUE TITLE
Package client js asset pipeline friendly

### ISSUE THREAD

**Issue by felixbuenemann** [faye/faye#323]
It would be great if the faye-browser.js was packaged in the gem under `vendor/assets/javascripts` or `app/assets/javascripts`. That way it would be possible to serve the asset directly from the gem instead of having to maintain a copy in the project which can easily get out of sync on gem upgrades.

I know that it's possible to load faye.js from the faye server, but in many reverse proxy setups only the /faye endpoint will be exposed so that it's not accessible.

**Comment by eriko-de** [comment]
For people looking into this on a recent version, the asset load path is now wrong and need to be adjusted as the js files are now in '/build/client/*'

We were able to fix it by changing it to:

```ruby
# in config/application.rb

faye = Bundler.load.specs.find { |s| s.name == 'faye' }
config.assets.paths << (faye.full_gem_path + '/build/client')
```
