### ISSUE TITLE
JS browser 1.1.0 version raise error, after disconnect from websocket server

### ISSUE THREAD

**Issue by le0pard** [faye/faye#356]
Problem:

http://monosnap.com/image/VCxF1n3CqB4Qo0cPvyKFZ4pIkVMaKP
http://monosnap.com/image/5QB39KXxsF4RZVMrBta7Jut6SA2vKG

Current code:

```js
this.client = new Faye.Client("" + Global.pusher.hostname + "/pusher", {
  timeout: 45,
  retry: 5
});

this.client.on('transport:up', this._transportUp);
this.client.on('transport:down', this._transportDown);
```

And call function, which doing:

```js
this.client.disconnect()
```

As I can see, influence dispatcher, because if I am increase `retry`, when error comes later.

**Comment by le0pard** [comment]
Checked: Such error is not raising by 1.0.3 browser js library.

**Comment by jcoglan** [comment]
I can't reproduce this error. Do you have a complete working example?

**Comment by jcoglan** [comment]
To attempt to reproduce the problem, I put this code in the Faye demo app:

```js
var bayeux = new Faye.Client('/bayeux');
bayeux.disconnect();
```

The client does not attempt to send anything via the transport layer because it's not connected yet. What are you doing with the client before calling `disconnect()` on it?

**Comment by le0pard** [comment]
Hello, @jcoglan . I made simple example, which reproduce problem:

```js
var client, inboxChannel;

client = new Faye.Client(Global.pusher.hostname + "/pusher", {
  timeout: 45,
  retry: 5
});

inboxChannel = client.subscribe("/inboxes/1", function() {
  return console.log('hello');
});

setTimeout((function() {
  inboxChannel.cancel();
  return client.disconnect();
}), 1000);
```

it is trace:

```js
Uncaught TypeError: Cannot read property 'sendMessage' of undefined

faye.min-98831eb15e76ddecd6ceb67382b85a95.js?body=1:1 

Faye.Dispatcher.Faye.Class._sendEnvelope

faye.min-98831eb15e76ddecd6ceb67382b85a95.js?body=1:1

 (anonymous function)
```
I think `retry: 5` in some way continue working, because if I change it to 10, error come later. If I changed `retry` to 2, when I have error after ~2 second.

**Comment by jcoglan** [comment]
Thank you. This should be fixed in https://github.com/faye/faye/commit/4dad37cf031eede2c698ded757888c06db39d885.

**Comment by le0pard** [comment]
Confirmed. Error disappear. Thanks!
