### ISSUE TITLE
Client connection

### ISSUE THREAD

**Issue by rokkit** [faye/faye#358]
Hello, I have initial setup of Faye with Ruby client and Thin server, like in the Getting Started.
All worked fine before I upgraded Faye to 1.10 version.
Now, a client starts to fire transport:down event. I set up timeout like this
```javascript
var faye = new Faye.Client("http://localhost:9292/faye", {timeout: 0})
subscription = faye.subscribe("/activity", function(data) {  ...  });
```

 When I add logging to all incoming actions in faye.ru, I see this:

![2015-02-01 20 13 11](https://cloud.githubusercontent.com/assets/1239378/5993070/ca034472-aa54-11e4-8c64-953db04c3c44.png)

I have only one open client connection and don't do anything, but I see that the log records and the "id" field increase. 
When the id reaches the value "Z", the "transport:down" event occurs and client loses a connection. 
This behavior seems very strange.

**Comment by jcoglan** [comment]
I've run the code as you describe. My server is as:

```rb
# Run this using:
# $ thin start -R faye.ru -p 9292

require 'faye'
Faye::WebSocket.load_adapter 'thin'

class Logging
  def incoming(m, c)
    p [:in, m]
    c[m]
  end
end

server = Faye::RackAdapter.new(mount: '/', timeout: 25)
server.add_extension(Logging.new)

run server
```

And my client is:

```js
var Faye = require('./build/node/faye-node');

var faye = new Faye.Client("http://localhost:9292/faye", {timeout: 0});
subscription = faye.subscribe("/activity", function(data) { });

faye.on('transport:up', function() { console.log('UP') });
faye.on('transport:down', function() { console.log('DOWN') });
```

Running these examples, the client script prints `UP` and continues to be connected indefinitely. I don't see a break when the ID passes `z`.

Is there something different about your setup that's causing the error?

**Comment by jcoglan** [comment]
Did you have any feedback on my last comment?

**Comment by jcoglan** [comment]
I'm going to close this due to lack of feedback, but if it continues to be a problem, do please re-open or file a new issue :)
