### ISSUE TITLE
Safari and Faye cause connections to remain in CLOSE_WAIT status

### ISSUE THREAD

**Issue by will-in-wi** [faye/faye#362]
I've written a test case here:
https://github.com/will-in-wi/test-socket-bug

We've been fighting a bug for a couple weeks which is causing Faye to take up large amounts of memory on production until Linux kills the process. When Safari is opened and closed with a Faye connection started `onready`, the connection remains in CLOSE_WAIT status for a long time.

I think that this is a Faye bug as I can't reproduce it in socket.io.

Please ask if you have any other questions.

Thanks!

**Comment by jcoglan** [comment]
This sounds like a duplicate of https://github.com/faye/faye-websocket-node/issues/38. Can you confirm?

**Comment by will-in-wi** [comment]
This looks like it may have fixed the issue. I'm going to test further and report back.

Thanks!

**Comment by will-in-wi** [comment]
It looks like the fix is working on stage. We are going to deploy to prod tomorrow morning. Are you doing a release any time soon?

**Comment by jcoglan** [comment]
I'm working on releases of all the faye modules at the moment but can't say for sure when they'll be out.

**Comment by will-in-wi** [comment]
That fixed it.
