### ISSUE TITLE
Some messages not getting through

### ISSUE THREAD

**Issue by mik977** [faye/faye#365]
I've encountered a problem with messages not getting through. 

I have a node client and server. Both on the same machine. 

On the client I have an interval function that runs every second and pushes 100 messages to a channel. However, not all messages get to the server. There is about 30-40% of message loss with this configuration.

If I try another configuration with an 100ms interval and 10 messages pushed, I have approx. 1% message loss.

In the last try with a 10ms interval and 1 messages pushed, I have only 10 out of 60k message loss.

I am sending approx 60000 messages in a simple 1 client configuration.
I am using the latest node 0.12 and the latest npm faye (1.1.1). 

All messages are transfrerred according to faye (publish reports no errors.)

Am I doing something wrong or...

(add)
Also tried publishing to the server client with same result. Some messages are swallowed without notice.

But this simple example works as expected:

var http = require('http'),
    faye = require('faye');

var server = http.createServer(),
    bayeux = new faye.NodeAdapter({mount: '/faye', timeout: 45});

bayeux.attach(server);
server.listen(8888);

var client = new faye.Client('http://localhost:8888/faye'); //bayeux.getClient();

client.subscribe('/test',function(msg){
        console.log(msg);
});

var msgNo=1;
setInterval(function(){
        for(i=0;i<50;i++){
                client.publish('/test',"This is the test message no. "+msgNo);
                msgNo++;
        }
},100);

So, I must be doing something wrong...

But then again, when using another library, that publishes through REDIS, everything is fine. 

Client                                       Server

msg -> REDIS                          REDIS -> msg                                          OK

msg -> fayeClient.publish        fayeClient(server client).subscribe           NOT OK (missing some)

msg -> REDIS                         REDIS ->msg ->fayeClient(server client).publish(msg) -> fayeClient(server client).subscribe                                                           NOT OK (missing some)

All the other parameters (loops, etc...) are the same.

I also found out that if one decreases the rate at which messages are sent, let say if I only send 5 messages every 100ms instead of 10, more messages pass through. And if you wait long enough between messages, all of them will pass.

My configuration uses websockets as transport. There are no proxyes or load balancers in between.
I am using Express 4.

If you need further info, I will be glad to provide it.

**Comment by jcoglan** [comment]
I'm not sure what you mean when you say that your script

```js
var http = require('http'),
    faye = require('faye');

var server = http.createServer(),
    bayeux = new faye.NodeAdapter({mount: '/faye', timeout: 45});

bayeux.attach(server);
server.listen(8888);

var client = new faye.Client('http://localhost:8888/faye'); //bayeux.getClient();

client.subscribe('/test', function(msg) {
  console.log(msg);
});

var msgNo = 1;
setInterval(function() {
  for (i = 0; i < 50; i++){
    client.publish('/test',"This is the test message no. " + msgNo);
    msgNo++;
  }
}, 100);
```

works as expected -- how does this script differ from the scenario you describe above that does not work?

Can you provide code for one of your tests that fails? Does this only happen when using the Redis backend, or also when using the in-memory engine?

**Comment by mik977** [comment]
I've changed my program to use another means of communication between two node apps in the meantime. Doing this I found out that I also significantly reduced CPU load. Maybe faye is not the best for node(.js) to node(.js) communication through Websockets. I'll try the simple example with the redis backend and let you know. Thanks.

**Comment by jcoglan** [comment]
Did you have any more feedback about this or should I close this issue?

**Comment by jcoglan** [comment]
I'm going to close this issue due to lack of feedback, but if you have more information that would help us solve the problem, please do re-open and leave comments :)
