### ISSUE TITLE
Problem catching disconnect message on firefox

### ISSUE THREAD

**Issue by clairezed** [faye/faye#366]
Hi,

I'm working on a rails 4.2 app using gem 'faye', '~> 1.0.3', gem 'faye-rails', '~> 2.0.0' and gem 'faye-redis', '~> 0.2.0', with a Thin server.

Everything works fine on Chrome. 
Everything works fine on Firefox except user disconnection. 
I identify disconnection based on incoming message on '/meta/disconnect/' channel and a home made timeout, but on Firefox disconnect messages are never sent.

**Investigations**
- I have systematically the following message on Firefox before unload : *"The connection to ws:://localhosot:3000/faye was interrupted while the page was loading"*. Could it prevent disconnect message being sent ?
- I noticed that disconnect message is sent and caught on Firefox if websocket is disabled (`faye.disable('websocket')`, client side). This works even as I have a similar error message in Firefox console (*"connection interrupted while the page was loading"*). But I'd be really sad if I had to forbid websocket, and would like to find an other, better solution.
- on Chrome, on each page change I have a POST request to faye followed by a GET request with status 101 (normal behaviour, as far as I know); on Firefox I have the same + another POST (status 200). I don't see much differences between the first 2, except on Switching protocol request, (Firefox `Connection = keep-alive, Upgrade` ; Chrome `Connection = Upgrade`). 

Here are the headers of the 3 faye request on Firefox : 
![screenshot from 2015-03-12 17 44 50](https://cloud.githubusercontent.com/assets/2668217/6622994/7a7a1b60-c8e0-11e4-8cfc-919ae0f1df31.png)

![screenshot from 2015-03-12 17 49 26](https://cloud.githubusercontent.com/assets/2668217/6623001/8860620c-c8e0-11e4-9a9d-115183839524.png)

![screenshot from 2015-03-12 17 49 41](https://cloud.githubusercontent.com/assets/2668217/6623000/84e31ff2-c8e0-11e4-839e-1cd015a20d9a.png)

I don't manage to understand where does the problem come from, if it's a bug or a problem of configuration, and any help would be welcome. I'll be glad to give further information on demand.

**Comment by antstorm** [comment]
:+1:

**Comment by clairezed** [comment]
I'm reassured to see I'm not the only one !
@antstorm Have you found a solution to deal with this problem ?

**Comment by antstorm** [comment]
@clairezed no, not really. I've tried debugging it myself, but it seems like Firefox never gets to emitting the disconnect event. Here are my findings on the issue — https://groups.google.com/forum/#!topic/faye-users/kiUwFR6B8ro

**Comment by jcoglan** [comment]
It's not unusual for the client's `/meta/disconnect` message to not reach the server, because the browser tears down the connection as the page unloads. This is very common in Firefox.

Because of this, Faye uses internal timeouts on the server to detect clients that have gone away without explicitly disconnecting, and reports their detection via the [monitoring API](http://faye.jcoglan.com/node/monitoring.html). You should use that to monitor disconnects, rather than relying on the wire messages.
