### ISSUE TITLE
Net::HTTP post returns successful even when client does not exist

### ISSUE THREAD

**Issue by mehulkar** [faye/faye#368]
We are using `HTTP` transport to publish from a Ruby client on the server to JS clients in the browser. 

When a JS connection is killed (by closing the browser, not an explicit call to `/disconnect`), and we send a `POST` to the channels subscribed to by that user is still successful. 

I'm not sure if this is a bug?

Basically, I need to know when there are no subscribers to a channel so I can close it down.

**Comment by mehulkar** [comment]
Related issue https://stackoverflow.com/questions/28981473/how-to-detect-a-killed-connection-to-faye-client

**Comment by jcoglan** [comment]
This is not a bug. The server only acknowledges that it received the message; it does not matter how many clients are subscribed to that channel.

See [the Bayeux specification][1] for more information on how the protocol works.

[1]: http://svn.cometd.org/trunk/bayeux/bayeux.html
