### ISSUE TITLE
net::ERR_EMPTY_RESPONSE on /meta/handshake faye 1.1.1 master

### ISSUE THREAD

**Issue by asmatameem** [faye/faye#370]
While I wait for the this fix (https://github.com/faye/faye/commit/cee6a778876da69ff958514b6591e6fcbf7481c1) to be released, I have been using faye by pointing it to the master branch. 

However, that does not build because gemspec requires the .js files to be there which are not present in the master branch. 

I downloaded the browser .js files from http://faye.jcoglan.com/download.html and added it to the lib directory after forking the gem. 

Even after all this, I am unable to get it to work. This is the error I see during the handshake phase: 

(failed)
net::ERR_EMPTY_RESPONSE

**Comment by jcoglan** [comment]
You can get the effect of running `master` by installing 1.1.1 from rubygems and then loading this:

```rb
class Faye::Server
  def scheme
    nil
  end
end
```

What are you doing to trigger this error? How are your server and client set up?

**Comment by jcoglan** [comment]
I'll shortly be doing a bug fix release so you shouldn't have to run Faye from source any more. I'm sorry for the delay. Can I close this issue, or is it still a problem?

**Comment by jcoglan** [comment]
I'm going to close this issue since it's not had any feedback since I last asked, but if you are still stuck on this issue then please do re-open it and leave further comments :)
