### ISSUE TITLE
How do I make it work with websockets and nginx?

### ISSUE THREAD

**Issue by x-yuri** [faye/faye#373]
I'm trying to make [this demo app](https://github.com/cwoodcox/faye-demo) work. It uses fairly old version of `faye`. But with it it more or less works (over websockets). But not with `nginx`.

```
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

server {
    server_name fa1;
    root /srv/http/fa1/public;
    try_files $uri @ruby;
    location @ruby {
        proxy_pass http://localhost:9292;
    }
    location = /faye {
        # try_files @uri @faye;
        proxy_pass http://localhost:9292;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection $connection_upgrade;
        proxy_set_header Connection 'upgrade';
    }
    location /faye/ {
        # try_files @uri @faye;
        proxy_pass http://localhost:9292;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        # proxy_set_header Connection $connection_upgrade;
        proxy_set_header Connection 'upgrade';
    }
    location @faye {
    }
}
```

When I delete `Gemfile.lock` and run it again (with the latest `faye`) it doesn't work over websockets even without `nginx`. What am I doing wrong? How to make it work? Thanks in advance.

P.S. [This app](http://nginx.com/blog/websocket-nginx/) works as they say.

**Comment by jcoglan** [comment]
As in #374, it's missing a `load_adapter` call from `config.ru`. Since that app was written, Faye added support for more app servers and you need to load an adapter for the one you're using.

You also don't need to run the app in production if you use `thin(1)` to run the app, as in:

```
$ thin start -R config.ru -p 9292
```

**Comment by x-yuri** [comment]
thank, the basic working example can be found [here](https://github.com/faye/faye/issues/374#issuecomment-90952913).

**Comment by x-yuri** [comment]
By the way, what did you mean by `thin(1)`?

**Comment by jcoglan** [comment]
I mean the `thin` executable. `(1)` is a short-hand for 'executable', in that it refers to section 1 of the man pages, which document executables. Section 2 is for syscalls, so `select(2)` refers to the `select` syscall, and so on for other man pages sections. You will often see this notation in any Unix-related documentation that refers to executables, syscalls, C library functions, and other things.
