### ISSUE TITLE
Custom message parsing

### ISSUE THREAD

**Issue by stringparser** [faye/faye#378]
Hello @jcoglan, 

Is it possible to `addExtension` to parse messages? Say you want to parse a regular expression :smile:.

Using node on the server.

**Comment by jcoglan** [comment]
No, only JSON is allowed over the wire.You could turn the regex into a string using `regex.source` and convert it back using `new RegExp(string)`.

**Comment by stringparser** [comment]
Thanks, that would work. So I'm guessing `JSON.parse` is used to deserialize right? I mean if its done [at this point](https://github.com/faye/faye/blob/master/javascript/adapters/node_adapter.js#L196) of the source code. I was thinking on using [ejson](https://github.com/primus/ejson). 

Would it be something of interest to make a hook for it on the prototype? If so, I'll do a PR.

**Comment by stringparser** [comment]
And by hook I mean, to write a simple `fromJSON` and `toJSON` function that would take care of that.

**Comment by jcoglan** [comment]
I meant that you should perform those conversions in your application, not bake them into Faye. Faye implements [Bayeux](http://svn.cometd.org/trunk/bayeux/bayeux.html), which mandates that all messages be encoded as JSON.

Allowing encodings other than JSON would require changes to:

* The `Adapter` class that takes messages off the wire via various HTTP-based transports
* The `Server` which would have to deal with messages containing arbitrary data types (and possibly arbitrary behaviour)
* The `Engine`, which assumes messages can be encoded as JSON and uses this to move messages between processes
* The client-side transport system and probably the client itself

All this would need to be done to both the JS and Ruby versions, and in any case, it would prevent Faye from interoperating with other Bayeux implementations that don't understand EJSON.

**Comment by stringparser** [comment]
I went to naively on things I see :). If it messes with Bayeux implementation itself is something to make aside. Thanks for the whole explanation @jcoglan.

**Comment by stringparser** [comment]
Just as a note, using `toString` was better than `.source` on the `RegExp`. To maintain the flags as well.
