### ISSUE TITLE
IE 8 XDomainRequest fails randomly

### ISSUE THREAD

**Issue by jkarneges** [faye/faye#382]
It seems that XDR sometimes gets garbage collected if there are no references to the object.

Explanation and workaround suggested here:
http://stackoverflow.com/questions/8058446/ie-xdomainrequest-not-always-work/27583212#27583212

The bug only affects IE 8, since XDR isn't in IE 7, and the GC issue seems to be gone in IE 9. I've only been able to reproduce it in IE 11's version 8 compatibility mode. I was unable to confirm using a VM running a real IE 8. Reproducibility also seems to be affected by the complexity of the page that Faye lives on (probably because other elements/scripts could affect GC timing).

The suggested fix in the stackoverflow post seems to work, in that if I add something similar to Faye's code them I'm unable to reproduce the issue anymore in IE 8 compatibility mode.

**Comment by jcoglan** [comment]
I'm closing this now that #383 is open.
