### ISSUE TITLE
Example not working?

### ISSUE THREAD

**Issue by huglester** [faye/faye#384]
Hello everybody,

I was fighting the thing, that I could not think  about, how to add some sort of server side timestamps. 
So when new user connects to the chat, I could show  him something like: "3 minutes ago" near the last  20 messages.

Tried to study examples, and  when trying to run run nodejs server, I get:
`Error: Cannot find module '../../build/node/faye-node'`

I did `npm install`, so deps should have been installed. Any ideas?

Thanks

**Comment by jcoglan** [comment]
Sorry, this does trip people up every so often. You need to build the package as described in [`CONTRIBUTING.md`](https://github.com/faye/faye/blob/master/CONTRIBUTING.md).
