### ISSUE TITLE
How to set `maxLength` option of faye-websocket using faye?

### ISSUE THREAD

**Issue by Kirill89** [faye/faye#386]
[faye-websocket](https://github.com/faye/faye-websocket-node#initialization-options) has `maxLength`, do faye has same? How to limit maximum size of message?

**Comment by jcoglan** [comment]
This setting isn't currently exposed in Faye. You can work around this by doing:

```js
var driver = require('websocket-driver/lib/websocket/driver/base');
driver.prototype.MAX_LENGTH = someNumber;
```

You might need to change the path to `websocket-driver` depending on how deep inside your `node_modules` it's installed.

**Comment by Kirill89** [comment]
@jcoglan thanks for your solution. Maybe `maxLength` in faye will be usable, do you think so?

**Comment by jcoglan** [comment]
I don't have any plans to add `maxLength` and it would probably require refactoring the options API for the server. I'd welcome a PR but it would have to wait until 1.2 since it's a feature addition.

**Comment by puzrin** [comment]
@jcoglan FYI `require('websocket-driver/lib/websocket/driver/base')` is broken with npm3, because it can optimize modules location (but as far as i know, there are no guarantee that module will be moved always)
