### ISSUE TITLE
Disconnect Not Working in Android Webview

### ISSUE THREAD

**Issue by dhakadamit** [faye/faye#389]
Firstly, thanks for the brilliant product.

I am using it on my android application via Webviews. When the app goes in background, I call client.disconnect() and subscription.cancel(). It works perfectly in Browser, on iOS devices, but not on Android.

On Android, the subscription is cancelled successfully. I see no updates after I open the app. However, I see that the data is being consumed when the app is in background. Its very minimal, like 1KB every 5s or so. However, that leads to MBs of data on a daily basis.

I need to completely stop Faye. I don't know what its doing. I don't even need it to ping or check connection or anything. Just stop completely.

**Comment by jcoglan** [comment]
I don't have any experience with Android but you do not need to call `subscription.cancel()` -- calling `client.disconnect()` implicitly cancels all the subscriptions.

What data is the client sending and receiving after you've called `client.disconnect()`? You can set `Faye.logger = console` (or some other logger-type object) to see what's going on.

**Comment by jcoglan** [comment]
Did you try my suggestion? Did you manage to find out anything more about what the client is doing?

**Comment by dhakadamit** [comment]
Yes. I did try out your suggestion. And it does seem to me that Faye is working fine. I am still debugging the issue. It seems to be an issue with Android. Thank you for the support.
