### ISSUE TITLE
No Result on the client

### ISSUE THREAD

**Issue by davidearlotto** [faye/faye#397]
Hi Guys, 
I'm new with faye web socket, and I tried to set up a server and a client to exchange information. Unfortunately I'm missing something and I can't get on the client the messages sent from the server. 
This is my server.js:
    
             
         var faye = require('faye');

          var Router = require('node-simple-router');
          var router = new Router();
          var server = require('http').createServer(router);
          var port = 5000;

          var bayeux = new faye.NodeAdapter({mount: '/faye/calls'});
          bayeux.attach(server);

          // Launch the server
          server.listen(port, function() {
               console.log('Listening on ' + port);
                      setInterval(function(){
                                 bayeux.getClient().publish('/faye/calls', {text: 'Hello'});
             },3000);

And is my client.js

             var faye = require('faye');

             var client = new faye.Client('http://localhost:5000/faye', {
                      timeout: 600,
                      retry: 5
             });
    
            var sub =  client.subscribe('/calls', function(message) {
                    console.log('message:' + message);
            });

            sub.then(function() {
                   console.log('overall Subscription is now active!');
            });

Can somebody please tell me what I'm missing?
Thanks very much

Have a good day

**Comment by jcoglan** [comment]
The URL you've set the server up on:

```js
var bayeux = new faye.NodeAdapter({mount: '/faye/calls'});
```

and the URL you're connecting the client to:

```js
var client = new faye.Client('http://localhost:5000/faye', {
```

don't match. It's possible that you meant `{mount: '/faye'}` in your server config.

The channel you're publishing on:

```js
bayeux.getClient().publish('/faye/calls', {text: 'Hello'});
```

and the channel you're subscribing to:

```js
var sub =  client.subscribe('/calls', function(message) {
```

also don't match. These need to be the same for your messages to get through. It's possible you meant to publish to `/calls` rather than `/faye/calls`.

**Comment by davidearlotto** [comment]
Thanks James, 
I understand the logic now. It worked
