### ISSUE TITLE
Ruby server uses 100% cpu

### ISSUE THREAD

**Issue by mulvaney** [faye/faye#401]
We have been running a Ruby based Faye server for a long time.  Recently the process starts running at 100% cpu and can't be stopped without a kill -9.

I have no idea what causes this, but it happens somewhat frequently -- at least once a day in production.  My suspicion is that some client is connecting that causes this runaway situation.  I do not think it is purely load related, because once it hits 100% it never comes back down.

Any tips on how to troubleshoot this?

**Comment by mulvaney** [comment]
I forgot to mention -- we are running under thin and ruby 2.2.3

**Comment by khadzhinov** [comment]
right now we have same issue... when faye starts on production - 100% cpu

**Comment by mulvaney** [comment]
We switched to the node server and haven't had any problems.  I don't have any more information about why the ruby server is using so much cpu, sorry.

**Comment by sodabrew** [comment]
What versions of the faye and eventmachine gems are you using? I am tracking an issue in eventmachine/eventmachine#607 that may be related.

**Comment by sodabrew** [comment]
Sorry, I meant to link to https://github.com/eventmachine/eventmachine/pull/445 which was released with EventMachine 1.0.4. Please update your eventmachine gem and let us know if it resolves this 100% CPU problem for you.

**Comment by khadzhinov** [comment]
I up faye and event machine version and all ok rgiht now

**Comment by sodabrew** [comment]
@jcoglan I think this issue can be closed :)

**Comment by khadzhinov** [comment]
Currently we have same issue so we turn faye off. I think problem right now in simultaneous connections, so we can't serve them.

**Comment by jcoglan** [comment]
I'm getting conflicting messages about whether EventMachine has fixed this issue -- should I close it or not?

**Comment by mulvaney** [comment]
I switched to the JavaScript version of Faye so I don't know if this is fixed in Ruby/event machine or not.

-Mike

**Comment by jcoglan** [comment]
@mulvaney in that case I'm going to close this issue, since it seems unlikely there'll be more feedback on it.
