### ISSUE TITLE
Issues when using different patch versions on client and server?

### ISSUE THREAD

**Issue by fatso83** [faye/faye#402]
I was about to upgrade to Faye 1.1.2 on server, and will also do so for new clients, but we have some clients that are stuck on 1.1.1 for the foreseeable future. Are there known problems with doing so?

**Comment by jcoglan** [comment]
There should not be, for a couple of reasons.

First (the weaker reason) is that I try to maintain backward compatibility in all releases, not just minor ones. 1.1.1 -> 1.1.2 should be a seamless upgrade.

Second, the client and server implement a standard protocol and both interoperate with other Bayeux implementations. As such, the client and server should not care which implementation, or version of an implementation, is running on the other end of the connection. The Faye client is not tightly coupled to the server, and vice versa.

**Comment by fatso83** [comment]
Thank you very much for that clarification.

Also a big :+1: to all the work you have put into making Faye usable!
