### ISSUE TITLE
spec tests using stub("setTimeout") dont wait for async testing

### ISSUE THREAD

**Issue by thesmart** [faye/faye#406]
I've noticed that `client_spec.js ` tests aren't waiting for tests with a `resume` argument and are exiting the test immediately.  Example, add this test somewhere in `client_spect.js`:

```js
it("should wait for resume", function(resume) { with(this) {
  console.info('should wait now...');
}})
```

The output looks like:

```
Loaded suite: Faye, Client

.......................................................should wait now...
smart$
```

And the terminal prompt is green, meaning it didn't cleanup after itself.  Looks like this has to do with stubbing the `setTimeout` method.

**Comment by jcoglan** [comment]
Turns out this is actually a bug in jstest, which is fixed in https://github.com/jcoglan/jsclass/commit/693ca6ce6048969915d5ff2f288fee88aa3af5ff.
