### ISSUE TITLE
Webworker

### ISSUE THREAD

**Issue by mikeptweet** [faye/faye#410]
Is it possible to get the browser client working in a WebWorker?

**Comment by jcoglan** [comment]
I don't know, I've never tried. Are you encountering any specific problem with it?

**Comment by jcoglan** [comment]
Do you have any further feedback on my last comment, or should I close this issue?

**Comment by mikeptweet** [comment]
Faye uses JSONP,(which isn't allowed in a worker) to initiate the websocket connection so it doesn't work. You can close this issue if you have no intentions of supporting web workers.

**Comment by jcoglan** [comment]
I don't actually know all that much about Web Workers and which transports would be usable in one. Can it use XHR and WebSocket? Hows does the same origin policy affect workers?

It won't be possible to support cross-origin connections because the Bayeux protocol requires JSON-P to make those connections, but same-origin might work.

If you're able to send a minimal example of getting a worker set up locally I could have a look into it.

**Comment by mikeptweet** [comment]
So in your main page ...

var client = new Faye.Client('http://localhost:8000/faye');

var worker = new Worker("http://localhost:8000.worker.js");


and worker.js should be

importScripts("http://localhost:8000/faye/client.js");
var client = new Faye.Client('http://localhost:8000/faye');

you can debug in chrome devtools by selecting the worker context in the
console

**Comment by jcoglan** [comment]
Turns out all we needed to make this work was to use the global `this` binding rather than `window` to refer to the global scope. b14b25417bf4ec97cce60b54f049193624be61ff makes your example code work in Chrome for me.

**Comment by jcoglan** [comment]
(Webpack converts `global` references to refer to the global object, whatever that is.)

**Comment by mikeptweet** [comment]
Awesome - thanks!

**Comment by mikeptweet** [comment]
any chance you can push this update out to npm?

**Comment by jcoglan** [comment]
I'm currently in the process of getting 1.2 ready and tying up loose ends. Far as I'm aware there's no major work left to be done, so it should be done soon.

One improvement I have made is that if you're using browserify/webpack, you can now `require()` Faye directly from the git repo without any build steps and you should get the right thing, if you want to try it out before release.
