### ISSUE TITLE
Uncaught error in middleware

### ISSUE THREAD

**Issue by matthisk** [faye/faye#411]
I have noticed some strange behavior when an error is thrown in messages intercepted by the middleware that contain a subscription property. The error is caught in some Promise but never propagated to the rejected handler in the Promise returned by `Faye.Client(URL).subscribe(PATH)`. This way the connection fails silently and keeps reconnecting. The following code snippet contains a middleware object that can cause this issue to arise:

```
var middleware = {
  ingoing : function(message, callback) { callback(message); },
  outgoing : function(message, callback) {
    if( message.subscription ) {
      throw new Error('');
    }  
  }
};
```

**Comment by jcoglan** [comment]
Users should handle errors in their code themselves. This is partly because many classes of errors that will occur in extensions will be asynchronous and cannot be caught by Faye.

**Comment by matthisk** [comment]
But what about introduction of a subtle bug like selecting unknown member on an object. The thrown error is now caught by the exception handler in the promise, but not propagated to the onRejected handler of the promise created by the subscribe function. Because the exception is caught the 'bug' is invisible when debugging the program.

**Comment by jcoglan** [comment]
I'm not sure what you mean when you say 'the exception handler in the promise', could you explain that more fully, and link to the code you're referring to?

If I write a client with the extension you've shown, for example:

```js
var faye = require('faye');

var client = new faye.Client('http://localhost:8000/bayeux');

client.addExtension({
  outgoing: function() {
    throw new Error('ext error');
  }
});

client.subscribe('/foo', function() {});
```

This program crashes because of the error in the `outgoing()` method; the error is not swallowed.

**Comment by jcoglan** [comment]
Did you have any feedback on my previous comment to clarify what you mean, or should I close this issue?

**Comment by matthisk** [comment]
You are right, I can not seem to reproduce this issue in a consistent manner on a code example with only very simple middleware. There must have been something else I was doing wrong before. Consider this question as solved.
