### ISSUE TITLE
bayeux protocol: broken link

### ISSUE THREAD

**Issue by igalic** [faye/faye#413]
Bayeux protocol links to http://svn.cometd.org/trunk/bayeux/bayeux.html
which is down. What's the new(?) canonical resource on this?

**Comment by jcoglan** [comment]
Thanks for spotting this. The last few times I've searched for this it seems to have moved again, but https://github.com/faye/faye/commit/2e130e400575475c2254aa693559126129aeb4db links to where it seems to be now.
