### ISSUE TITLE
Faye Extension project

### ISSUE THREAD

**Issue by ginjo** [faye/faye#415]
I've been modularizing my core Faye tools (ruby) to the point where they are fitting nicely into a gem who's primary focus is a class for Faye::Extension. This gem provides two enhancements for Faye: 1, an Extension class that makes creation of server extensions even easier, moving common code into helper methods. 2, provides further helpers to facilitate Faye functionality that is universal to all of my projects, especially where extensions are concerned.

I've gathered up a number of questions along the way. I know there is a lot to consider here, so I don't expect a fully comprehensive answer to all of them. Instead, I'll just jot down the questions, and post them for all to consider.

I'm particularly interested in jcoglin's thoughts on this, especially if he has objections to my creation of a 'faye-extension' gem. Is a faye-extension gem a useful addition to the community, or should I maintain it as a private implementation for my specific projects? Or should I offer the Extension class as a PR to the Faye gem?

The current code is [here on github](https://github.com/ginjo/faye-extension-ruby).

So, here are my amassed questions (with a big thanks for the outstanding Faye project!).
- Is there a use case for mutliple adapters/servers in a single process?
- Should Faye extensions always be added to every running adapter,
  or could there be a case where two adapters running in same process
  would have different extensions?
- Is clientId an appropriate string to use as a client-specific
  channel for private client-server communication?
  
  ```
  client.subscribe("/ak3kdkfjlksd89f98s98dflkjfdfkjkjsd8f78s7dfk")
  ```
  
  Basically, I subscribe every client to it's own private channel,
  whenever the client opens a connection.
  
  This has been working very well for me, as server-extensions
  always know where to send client-specific messages. And so far,
  no cliendId's are leaked to any other clients.
- Is the following seperation-of-concerns appropriate for Faye?
  
  I have created an architecture where Faye is only concerned with
  who gets what message. No part of my Faye system has any knowledge
  of what to do with the messages or what they mean. Message processing
  is handled by a separate layer on both client and server.
  
  Under this architecture, any channel on any client could potentially
  receive any kind of message (chat, data-update, alert, etc..). It's
  up to my message-processing layer to determine what to do next.
- Some of the helpers in faye-extension make use of direct calls to Redis.
  I understand this is treading on unstable ground... But is this acceptable
  practice in the domain of a 'gem', where responsiblity for upkeep and
  compatibility is centralized and well-defined?

**Comment by jcoglan** [comment]
Sorry it took so long for me to get to this issue but I'll try to answer your questions. Of course I'd like you to release your gem if you find it useful :)

> Is there a use case for mutliple adapters/servers in a single process?

I'm not aware of one, unless you want multiple logical Faye services with their own channel spaces. Faye uses EventMachine so each server runs in the same thread, and inside the server, most of the work is CPU-bound so you gain little by running it in multiple threads anyway (on MRI). If you want to run multiple servers you'll get more mileage running them in separate services.

> Should Faye extensions always be added to every running adapter,
or could there be a case where two adapters running in same process
would have different extensions?

If the adapters are part of the same logical service and a load balancer might cause a client to connect to any of them, then they should probably all look the same.

> Is clientId an appropriate string to use as a client-specific
channel for private client-server communication?

This might work, and you may not be leaking IDs, but I'd advise you not to do it. The ID of a single client object can change over time, if it gets disconnected from the server and its session times out and it has to handshake again.

> Is the following seperation-of-concerns appropriate for Faye?

It sounds entirely reasonable to me to have your application as loosely coupled to your messaging infrastructure as possible. This makes it easier to change your mind, and makes it easier to test your application components without needing to spin up Faye: you just pass messages into the app and it doesn't need to worry about where those messages came from.

> Some of the helpers in faye-extension make use of direct calls to Redis.
I understand this is treading on unstable ground... But is this acceptable
practice in the domain of a 'gem', where responsiblity for upkeep and
compatibility is centralized and well-defined?

It is breaking an abstraction boundary. As long as you understand you're taking a risk and are responsible for reacting to changes that break your gem, then that's fine.

**Comment by ginjo** [comment]
Thanks for the thoughtful answers! I'll mull these over and apply your advice to the gem-in-progress.

**Comment by jcoglan** [comment]
Should I close this issue, or did you have further questions?

**Comment by ginjo** [comment]
Thanks @jcoglan , I'm good for now, you can close it.
