### ISSUE TITLE
Faye server logging

### ISSUE THREAD

**Issue by andreyshade** [faye/faye#418]
How to enable Faye server logging? Please help.

**Comment by jcoglan** [comment]
Which version of Faye are you running -- Node or Ruby?

**Comment by andreyshade** [comment]
I use Ruby
17.12.2015 20:43 пользователь "James Coglan" <notifications@github.com>
написал:

**Comment by jcoglan** [comment]
Then you need to set `Faye.logger` to be a logger object, for example

```rb
Faye.logger = Logger.new(STDOUT)
```

Anything that conforms to the `Logger` interface should work.

**Comment by andreyshade** [comment]
Thanks, i try this
17.12.2015 20:47 пользователь "James Coglan" <notifications@github.com>
написал:

**Comment by jcoglan** [comment]
Did my last comment solve your problem? Can I close this issue?

**Comment by andreyshade** [comment]
Yes, you can close this issue. Thanks
