### ISSUE TITLE
"Invalid channel" error no matter what channel I use

### ISSUE THREAD

**Issue by JohnMerlino1** [faye/faye#419]
I am getting an error when doing the most basic test with faye:

$ curl http://localhost:9292/faye -d 'message={"channel":"checkins/create","data":"hello"}'
[{"channel":"checkins/create","successful":false,"error":"405:checkins/create:Invalid channel"}]

$ curl http://localhost:9292/faye -d 'message={"channel":"messages/new","data":"hello"}'
[{"channel":"messages/new","successful":false,"error":"405:messages/new:Invalid channel"}]

Why is faye producing this error no matter what channel I create?

**Comment by jcoglan** [comment]
It's because those channel names are not valid. Channel names must begin with `/`, so `/checkins/create` would be valid, for example.
