### ISSUE TITLE
Faye Server sends `Connection: close` header

### ISSUE THREAD

**Issue by suprememoocow** [faye/faye#420]
In this commit, from 2012: https://github.com/faye/faye/commit/a5c316231a1733a48e327888d781ef2c32913749, `Connection: close` was added to the response headers that the Faye server sends out.

I was wondering what the reasoning behind this was? Is it to deal with client incompatibilities? Closing the connection adds extra overhead to the client, and particularly the server, for long-polling and callback-polling responses, especially over TLS. 

Experimenting on my local Faye (js) server, removing `Connection: close`, I've found things to be much faster. For example, in one test, publishing 100 messages in sequence, using long-polling only, the test is about 40% faster. In the real-world, with higher round trip times I suspect this difference would increase.

Having said that, I'm not really interested in gaining extra performance, more in reducing unnecessary server load in having to setup new TCP sockets and TLS sessions for multiple connections from the same client (currently, we're averaging about 20 faye HTTP requests per second and it's growing fast). Removing `Connection: close` should mean a single TCP connection with a single TLS session, unless I'm missing something here?

**Comment by jcoglan** [comment]
To be honest, I don't recall why that was added, and if it produces the improvements you claim I'm happy to remove it and reconsider if anyone reports problems as a result.

https://github.com/faye/faye/commit/d97c3a949e2d09ea38c48bb56d7f112e171b61a2

**Comment by suprememoocow** [comment]
Thanks James. I'll run this change on the Gitter staging environment and keep an eye out for any oddness.

**Comment by jcoglan** [comment]
Just letting you know 1.2.0 has been released: https://groups.google.com/forum/#!topic/faye-users/_0kTHXciUGs
