### ISSUE TITLE
Node faye-couchbase lib

### ISSUE THREAD

**Issue by kvaillant** [faye/faye#422]
Hi,

I would like to thank you for all the great work you did around faye and modules.
For my concerns, I developed a faye-couchbase lib as a new faye engine in touch with couchbase.

Would you be interested in having a look into my repo and add to faye website as a new engine solution for faye.
https://www.npmjs.com/package/faye-couchbase
https://github.com/kvaillant/faye-couchbase-node

Please to hearing from you !

**Comment by jcoglan** [comment]
Sure, here you go: https://github.com/faye/faye/commit/95dfcfa7d2f229ed2766837645814be3c0846f8e

Thanks for the new engine :)
