### ISSUE TITLE
Transport goes down after a successful publish

### ISSUE THREAD

**Issue by yanhackcode15** [faye/faye#423]
Is it expected that the transport goes down after a successful publish? Here is my code:
    EM.run {

      client = Faye::Client.new('http://localhost:9292/faye')

      //Do something here on rails server before publish

        publication = client.publish("/meters/update", {
          'meter_id' => meter['meter_id'],
          'event_type' => meter['event_type'],
          'event_time' => meter['event_time']
        })

        publication.callback do
          puts 'Socket success'
          EM.stop
        end

        publication.errback do |error|
          puts 'Socket error: ' + error.message
        end

        client.on 'transport:down' do
          puts 'Socket error: Connection down'
        end

      end

    }
Rails server then puts Socket success followed by 'Socket error: Connection down'. I'm not sure whether the connection just goes down automatically after a successful publish and subscribe or is it something run with how I'm using it.

**Comment by yanhackcode15** [comment]
Also when I removed EM.stop line, transport still goes down.

**Comment by jcoglan** [comment]
Sorry, I can't reproduce this error against `master`. When I run the script (with `EM.stop` removed), `transport:up` is triggered and then the publication succeeds.

Is there something missing from your example that's needed to trigger the error you're seeing?

**Comment by yanhackcode15** [comment]
It's working now. I don't remember what I did differently. I did remove EM.stop.
