### ISSUE TITLE
Faye not working on heroku

### ISSUE THREAD

**Issue by yanhackcode15** [faye/faye#424]
Faye isn't working properly on heroku. I had faye working locally and was able to publish and sub to message.

I can see faye server booting up from heroku logs but after a publish from the rails server client, I'm not getting the callback which puts a message.

I'm not sure what's missing. The configuration locally should have worked.

Are there anything I should do differently to configure faye on heroku?
Here are a few things I did: 
application.js: 
//= require faye

application.rb: I added the following 2 lines
    config.middleware.delete Rack::Lock
    config.middleware.use FayeRails::Middleware, mount: '/faye', :timeout => 25

Procfile: 
web: bundle exec rails server thin -p $PORT -e $RACK_ENV
faye: bundle exec rackup faye.ru -s thin -E production

Rails server client creation and publishing:
EM.run {
      client = Faye::Client.new('http://localhost:9292/faye')
      publication = client.publish("/meters/update", {
          'meter_id' => meter['meter_id'],
          'event_type' => meter['event_type'],
          'event_time' => meter['event_time']
        })

       publication.callback do
          puts 'Socket success'
       end
}

I'm seeing in the logs that faye is up and running on heroku but my publish isn't getting the callback message.

**Comment by jcoglan** [comment]
It looks like you have a separate rackup file for Faye but you also have `FayeRails::Middleware` in your Rails stack, in `application.rb`. Is there a reason for that? (I should mention I don't know anything about how faye-rails works.)

**Comment by yanhackcode15** [comment]
I've taken care of the heroku issue now. It has to be do with setting the faye server domain to the production domain and setting the port number to use the heroku ENV var $port. Closing

**Comment by soumyaray** [comment]
@yanhackcode15 could you give a few more details about what this entailed? if you are running on Heroku could you not have simply set the server name to the production server name (e.g., `Faye::Client.new('my-app.herokuapp.com/faye')`)?  You shouldn't have to specify a port, right?
