### ISSUE TITLE
it is possible communication between  node.js servers ?

### ISSUE THREAD

**Issue by etmind** [faye/faye#429]
i have running few node.js servers on separate machines, it is possible set one server as master other as   clients and communicate over faye without web browsers ? thanks

**Comment by jcoglan** [comment]
Yes. You create a Faye server on one of your hosts:

```js
var faye = require('faye'),
    http = require('http');

var bayeux = new faye.NodeAdapter({mount: '/'}),
    server = http.createServer();

bayeux.attach(http);
http.listen(8000);
```

Then use the Client from Node on your other hosts to connect to that server:

```js
var faye = require('faye');

var client = new faye.Client('http://server-host:8000/');

client.subscribe('/foo', function(message) {
  // etc
});
```

**Comment by jcoglan** [comment]
I'm going to close this issue since I believe I've answered your question, but please leave another comment if you need more help :)
