### ISSUE TITLE
EventMachine 1.2.0 has been released!

### ISSUE THREAD

**Issue by sodabrew** [faye/faye#430]
Hi there! I've released EventMachine 1.2.0, which merges in the major work from EventMachine-LE 1.1.x, including better support for IPv6 and SSL/TLS. Please give it a try with Faye to make sure I haven't broken anything for this downstream library!

**Comment by jcoglan** [comment]
Thanks a lot for the heads-up :) I've just updated and run the tests, and everything looks okay!
