### ISSUE TITLE
Ruby client doesn't make connection to remote server (EM >= 1.2)

### ISSUE THREAD

**Issue by jamesotron** [faye/faye#435]
So I'm still trying identify the source of this problem, however the following script:

```ruby
require 'eventmachine'
require 'faye'

@exit_code = 0
EM.run do
  client = Faye::Client.new('http://localhost:4000/pixie')

  publication = client.publish("/test", {
    "hello" => "world"
  })
  publication.timeout(1)

  publication.callback do
    EM.stop_event_loop
  end
  publication.errback do |error|
    @exit_code = 1
    EM.stop_event_loop
  end
end

exit(@exit_code)
```

works fine when I use eventmachine 1.0.9.1 and below, but times out on 1.2.0 and above. It never actually makes the outgoing HTTP connection (I can prove this because `nc -l 4000` doesn't exit).

Posting here in case someone else comes across the same problem and can't figure it out.

I'll update this issue as I figure more out about it.

**Comment by jcoglan** [comment]
I can't reproduce this issue on my local machine running EventMachine 1.2.0.1 on the server and client. I've tried running the server with Thin, Puma, Rainbows and Goliath and they all work. I've also tried running against the Node.js server and that's fine.

If you do find out what's causing this I'll accept a PR. Sorry I can't be more help right now.

**Comment by jamesotron** [comment]
Sweet. I'll close this for now.

**Comment by jcoglan** [comment]
Just letting you know 1.2.0 has been released: https://groups.google.com/forum/#!topic/faye-users/_0kTHXciUGs

**Comment by jamesotron** [comment]
Thanks!
