### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by tpham812** [faye/faye#438]
I noticed that memory usage increases every time I publish a message. I am publishing every second. What can be causing this? Is it a memory leak?

**Comment by jcoglan** [comment]
Do you have some example code that demonstrates the issue happening?

I'd expect memory to increase initially as messages allocate memory and are stored inside the server waiting for other clients to retrieve them. As the server keeps running, GC runs should free up memory for reuse and so memory usage should stabilise.

**Comment by jcoglan** [comment]
Did you have any feedback on my previous question, or should I close this issue?

**Comment by jcoglan** [comment]
I'm going to close this issue due to lack of feedback, but if you do want to discuss it further then please do re-open it :)
