### ISSUE TITLE
Release 1.1.3?

### ISSUE THREAD

**Issue by javan** [faye/faye#439]
There are quite a few commits (https://github.com/faye/faye/compare/1.1.2...master) that haven't been released yet. Any plans to cut a new version? I've locked a number of projects (https://github.com/rails/rails/commit/20c14c5f13704245c124310ce1edc035e0104e75, https://github.com/basecamp/trix/commit/774b218a876d472261b97bdbd00889b66a2d1dfb) to 1.1.1 to avoid https://github.com/faye/faye/issues/394 in 1.1.2.

Thanks for your consideration! ❤️

**Comment by jcoglan** [comment]
I'm sorry there hasn't been a release for a while. I'm trying to finish up 1.2.0 -- there are a lot of changes on master that are too much for a patch release, including some substantial changes to the JS codebase.

One improvement that's in `master` is that if you're running browserify or webpack to build your project, `require('faye')` should get you the client without needing a build step in the Faye repo, so you can install it straight from git.

Could I ask why Rails is depending on Faye? I thought ActionCable was only going to use websocket-driver.

**Comment by javan** [comment]
No worries, and thanks for the update.

> I thought ActionCable was only going to use websocket-driver.

That's still correct. Action Cable and Trix both use Blade (https://github.com/javan/blade) as a JavaScript build and test tool. Blade uses Faye for its test runner. So Faye isn't a dependency for Rails apps, just a dev dependency for testing and releasing Action Cable.

**Comment by jcoglan** [comment]
I'm going to close this as I'm tidying things up before getting 1.2.0 out.

**Comment by jcoglan** [comment]
Just letting you know 1.2.0 has been released: https://groups.google.com/forum/#!topic/faye-users/_0kTHXciUGs
