### ISSUE TITLE
URI#find_proxy returns a URI, rather than a string

### ISSUE THREAD

**Issue by liudangyi** [faye/faye#448]
https://github.com/faye/faye/blob/master/lib/faye/transport/transport.rb#L20:

      @proxy[:origin] ||= @endpoint.respond_to?(:find_proxy) ?
                          @endpoint.find_proxy :
                          nil

`@endpoint.find_proxy` returns a URI.

https://github.com/faye/faye/blob/master/lib/faye/transport/http.rb#L57:

      if @proxy[:origin]
        uri = URI.parse(@proxy[:origin])
        options[:proxy] = {:host => uri.host, :port => uri.port}
        if uri.user
          options[:proxy][:authorization] = [uri.user, uri.password]
        end
      end

`URI.parse` only accepts string, which causes an error.

**Comment by jcoglan** [comment]
Thanks for reporting this. It's fixed in c0e1359.
