### ISSUE TITLE
A time wasting,  easy to fix issue: there's no exception if data isn't provided in publish(...)

### ISSUE THREAD

**Issue by dharmax** [faye/faye#449]
i wasted HOURS just because of that... Please, for the sake of humanity, just properly document the fact that data is mandatory and throw an exception if such was not provided....

**Comment by jcoglan** [comment]
I've made a change in 3615453 that makes the server return an error for published messages with no `data` field. This should result in you seeing rejected promises from `publish()`:

```js
client.publish('/foo').catch(function() {
  // handle error
})
```

**Comment by dharmax** [comment]
@jcoglan i apologize if it sounds inflammatory - it was totally not the intention, it was actually humorous, but i see now that it doesn't look that way from the reader point of view - sorry!
