### ISSUE TITLE
Can you remove multi_json ?

### ISSUE THREAD

**Issue by tumayun** [faye/faye#450]
See https://github.com/rails/rails/pull/10576

**Comment by jcoglan** [comment]
MultiJson was originally introduced reluctantly after requests from users -- I wanted to just depend directly on yajl, but people had various use cases for using other libraries. This is especially important for JRuby compatibility.

It's unlikely I'd remove this unless it posed a serious problem.

**Comment by jcoglan** [comment]
Should I close this issue, or is this something we should discuss further?

**Comment by jcoglan** [comment]
I'm going to close this since there was no response to my last question, but if you do want to discuss it further, do please re-open the issue :)
