### ISSUE TITLE
Logging request failures (node_http)

### ISSUE THREAD

**Issue by cwmunn** [faye/faye#453]
Hi!

It would be great if the error provided from `request.on('error')` in the node_http transport was logged. This can help quickly identify some basic issues that are easy to solve once you know what they are (ex. fail to resolve DNS)

Thanks for a great lib.

Cheers,
~Chris

**Comment by jcoglan** [comment]
I've added a little logging message in 2afb2db -- please let me know if that would work for you.

**Comment by cwmunn** [comment]
Perfect, thanks a lot!
