### ISSUE TITLE
Frequent transport:down

### ISSUE THREAD

**Issue by ackr1201** [faye/faye#454]
Hi ,

Am facing a frequent "transport:down" issue at my faye client. Please find my client as

Client is on ruby(sinatra) & faye (1.1.1)

```
client = Faye::Client.new <faye-server-endpoint>

EM.run {
  client.bind 'transport:down' do
    puts "Transport is DOWN!!"
    exit
  end
  client.bind 'transport:up' do
    puts "Transport is UP!!"
  end

  subscription = client.subscribe("/<channel>/*") do |message|
    puts "Received message from upstream: " + message.inspect
    # <perform some operation>
  end

  subscription.callback do
    puts "Subscription is successful"
  end

  subscription.errback do |error|
    puts "Subscription is unsuccessful."
    exit
  end
}

```

My server looks like

server is on node => "0.10.x", faye => "1.1.0", faye-redis => "0.2.0"

```

var server = http.createServer(function (request, response) {
var path = url.parse(request.url).path;
    switch(path){
      case '/':
        response.writeHead(200, {
          'Content-Type': 'text/plain'
        });
        response.end('Server running');
        break;
    }
    
  });

  var bayeux = new faye.NodeAdapter({
    mount: "/faye",
    timeout: 45,
    engine: {
      type: fayeRedis,
      host: "localhost",
      port: 3306
    },
    ping: 10
  });

  bayeux.attach(server);

  server.listen(config.faye.port);
```

My server is behind ELB & haproxy.

Can you please suggest. what might be the problem in my client/server ?

**Comment by jcoglan** [comment]
My advice would be to connect to your server directly, and then via ELB, and then via HAProxy, to find out if the issue if with the Faye server itself or one of your load balancing proxies.

**Comment by jcoglan** [comment]
Did you try my suggestion in my previous comment? Do you have any further input on this issue or should I close it?

**Comment by ackr1201** [comment]
For now we can close this. We will reopen this once we see this issue again.
