### ISSUE TITLE
requesting new gem release

### ISSUE THREAD

**Issue by stepheneb** [faye/faye#455]
Am requesting a new gem release to help work around the following issue.

Summary: the build directory isn't created using a faye gem loaded with bundler and a Gemfile spec using a git ref with commit -- which means serving bayeux/client.js fails.

I'm starting a development effort by adapting the ruby example chat server code and need the fix in bd01bc7c. This shouldn't be a problem if I specify this commit in my Gemfile spec for faye:

    gem 'faye', :git => 'https://github.com/faye/faye.git', :ref => 'bd01bc7c'

The problem fixed in bd01bc7c disappears but a new problem appears -- loading http://localhost:9292/bayeux/client.js returns a 404 error.

Hmmm ... so I change the gem spec to:

    gem 'faye', '1.2.3'

and manually edit dispatcher.rb to use:

    @endpoint = String === endpoint ? URI(endpoint) : endpoint

and everything works.

To try and understand the issue I change the gemspec to use the commit hash for the 1.2.3 tag:

    gem 'faye', :git => 'https://github.com/faye/faye.git', :ref => '4dfcc55'

and again manually edit dispatcher.rb to use:

    @endpoint = String === endpoint ? URI(endpoint) : endpoint

Same problem, loading the html page works but trying to load http://localhost:9292/bayeux/client.js returns a 404 error.

For now my problem could be solved with a new gem release.

It appears that when bundler loads the faye gem through a git reference the build directory isn't created.

    $ ls -l ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/faye-1.2.3
    total 48
    -rw-r--r--  1 stephen  staff  17290 Oct 20 16:57 CHANGELOG.md
    -rw-r--r--  1 stephen  staff   1543 Oct 20 16:57 README.md
    drwxr-xr-x  3 stephen  staff    102 Oct 20 16:57 build
    drwxr-xr-x  4 stephen  staff    136 Oct 20 16:57 lib

    $ ls -l ~/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/faye-4dfcc5572a56
    total 120
    -rw-r--r--   1 stephen  staff  17290 Nov 16 20:13 CHANGELOG.md
    -rw-r--r--   1 stephen  staff    162 Nov 16 20:13 CODE_OF_CONDUCT.md
    -rw-r--r--   1 stephen  staff   1010 Nov 16 20:13 CONTRIBUTING.md
    -rw-r--r--   1 stephen  staff     38 Nov 16 20:13 Gemfile
    -rw-r--r--   1 stephen  staff   1563 Nov 16 20:13 Makefile
    -rw-r--r--   1 stephen  staff   1543 Nov 16 20:13 README.md
    -rw-r--r--   1 stephen  staff    598 Nov 16 20:13 Rakefile
    drwxr-xr-x   9 stephen  staff    306 Nov 16 20:13 examples
    -rw-r--r--   1 stephen  staff   5707 Nov 16 20:17 faye.gemspec
    drwxr-xr-x   4 stephen  staff    136 Nov 16 20:13 lib
    -rw-r--r--   1 stephen  staff   1444 Nov 16 20:13 package.json
    drwxr-xr-x   5 stephen  staff    170 Nov 16 20:13 site
    drwxr-xr-x   8 stephen  staff    272 Nov 16 20:13 spec
    drwxr-xr-x  10 stephen  staff    340 Nov 16 20:13 src
    -rw-r--r--   1 stephen  staff    234 Nov 16 20:13 webpack.config.js

**Comment by jcoglan** [comment]
I will put out a new release as soon as I have time to do so. In the meantime, as it mentions in the [gemspec](https://github.com/faye/faye/blob/master/faye.gemspec) and the [contributing guide](https://github.com/faye/faye/blob/master/CONTRIBUTING.md), you need to run `make` in the gem's root directory to build the JavaScript client.

**Comment by stepheneb** [comment]
I'll use 1.2.2 for now. I'd prefer not to have to complicate the scripts for building the production server (example: installing the dependencies for making the gem).

If it turns out I need the newer unreleased gem I'll make it myself and check it into the repo for now.

**Comment by jcoglan** [comment]
Apologies for the delay, but I will be releasing a new version shortly -- look out for 1.2.4.
