### ISSUE TITLE
csrf token protection

### ISSUE THREAD

**Issue by DrakenZA** [faye/faye#457]
https://faye.jcoglan.com/security/csrf.html

Ive been trying to implement this as per the page.

But for some reason, the token im getting from the 'session' is different from the 'message', and its coming from the same PC/browser ?

**Comment by jcoglan** [comment]
Without seeing your code I'm not sure what to advise. Can you show me a small demo that illustrates the problem you're having?

**Comment by DrakenZA** [comment]
Hey thanks for the reply :) I was able to sort of the issue myself, i suggest you update the CSRF Protection doc stuff on the site. Seems newer versions of rails simply dont let you compare the token direct, it takes some manipulation.

`# Faye extension to verify CSRF token
class CsrfProtection
  def incoming(message, request, callback)
    session_token = request.session['_csrf_token']
    # getting encoded token and deleting from session data
    message_token = message['ext'] && message['ext'].delete('csrfToken')

    unless valid_token?(session_token, message_token)
      message['error'] = '401::Access denied'
    end

    callback.call(message)
  end

  private

  def valid_token?(session_token, message_token)
    # decode tokens
    masked_token = Base64.strict_decode64(message_token)
    real_token = Base64.strict_decode64(session_token)

    one_time_pad = masked_token[0...32]
    encrypted_csrf_token = masked_token[32..-1]
    # XOR  decypher
    csrf_token = xor_byte_string(one_time_pad, encrypted_csrf_token)

    ActiveSupport::SecurityUtils.secure_compare(csrf_token, real_token)
  rescue
    false
  end

  def xor_byte_string(s1, s2)
    s1.bytes.zip(s2.bytes).map { |(c1,c2)| c1 ^ c2 }.pack('c*')
  end
end`

Also, ive changed my personal usage of this to an if instead of an unless. For some reason, with the unless, it doesnt seem like the client ever gets told 'no' and it simply keeps trying, spamming the webserver.

**Comment by jcoglan** [comment]
is there an API in Rails that lets you compare the bare value to its encoded form, rather than doing the decoding yourself? I assume this random masking was added to defeat chosen ciphertext attacks on compressed data like CRIME and BREACH?

**Comment by DrakenZA** [comment]
http://apidock.com/rails/ActionController/RequestForgeryProtection/valid_authenticity_token%3F

Ya this is used i believe, but ive tried to 'call' it in many different ways from the CSRF Protection 'Extension' but it simply says it doesnt exist.

**Comment by jcoglan** [comment]
How were you trying to call it? If it's defined in a module, you need a concrete class/object to call it on; how were you doing that?

**Comment by DrakenZA** [comment]
ActionController::RequestForgeryProtection.valid_authenticity_token()

was how i was calling it. What would be the way that is correct and works ?

**Comment by jcoglan** [comment]
Oh, I didn't realise it was a class method from the docs. If it's a protected method, then the only way to call it is if `self` is a `Module` (or inherits from it). Protected class methods are weird, but maybe implementing a class method on your own extension to wrap it would work?

**Comment by DrakenZA** [comment]
I'm pretty new to web dev and dev as a whole :) not sure what u mean :)

On 04 Dec 2016, at 2:47 AM, James Coglan <notifications@github.com> wrote:

Oh, I didn't realise it was a class method from the docs. If it's a
protected method, then the only way to call it is if self is a Module (or
inherits from it). Protected class methods are weird, but maybe
implementing a class method on your own extension to wrap it would work?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/faye/faye/issues/457#issuecomment-264676156>, or mute
the thread

**Comment by jcoglan** [comment]
Okay, on inspecting the Rails source I'm not sure you can call it from outside the Rails stack. It's actually an instance method inside `RequestForgeryProtection`, which means you can only call it from objects that include that module. That's really frustrating and different from how the other session and encryption stuff in Rails works.

**Comment by DrakenZA** [comment]
Ya it's a bit silly. I can confirm though the way I described works :)
Thanks for coding a great project !

On 04 Dec 2016, at 3:04 AM, James Coglan <notifications@github.com> wrote:

Okay, on inspecting the Rails source I'm not sure you can call it from
outside the Rails stack. It's actually an instance method inside
RequestForgeryProtection, which means you can only call it from objects
that include that module. That's really frustrating and different from how
the other session and encryption stuff in Rails works.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/faye/faye/issues/457#issuecomment-264676845>, or mute
the thread

**Comment by jcoglan** [comment]
I've looked into this and found there's an easier way to do it where you just call Rails' own validation method, rather than reproducing its internal workings: https://github.com/faye/faye/commit/8861ffcd3ce0077d289556746bf59bfed990fe13

Thanks a lot for bringing this to my attention :)
