### ISSUE TITLE
Get latest message immediately after a subscription?

### ISSUE THREAD

**Issue by KENZoft** [faye/faye#460]
Is it possible to get the latest message on a channel immediately after a new subscription like the mqtt retain flag?

**Comment by jcoglan** [comment]
There's nothing like that built in, but you could implement it as an extension.

Having said that, Bayeux has no guarantee on message ordering, so the concept of "last message on a channel" is not well-defined unless you're running a single server.

**Comment by KENZoft** [comment]
Thanks for quick reply!
This is an IoT-project with one server and only one publisher for each channel. I have implemented an 'in memory cache' on the server and it works fine but only for absolute subscriptions and not wildcard subscriptions. I'll think about it :)

**Comment by jcoglan** [comment]
You could approach wildcards in the same way Faye's internal engine does: when a message arrives, you expand its channel into all the subscriptions that it might match, and then push the message to anyone subscribed to those.

e.g. the channel `/foo/bar/qux` would match these subscriptions:

* `/foo/bar/qux`
* `/foo/bar/*`
* `/foo/bar/**`
* `/foo/**`
* `/**`

**Comment by KENZoft** [comment]
Sounds like a very good idea! Thanks for the input!!
