### ISSUE TITLE
nodejs clients appear orphaned after a while

### ISSUE THREAD

**Issue by carlnordenfelt** [faye/faye#461]
Hi,

This is more of a question than an issue at the moment but we've been experiencing a strange behaviour that perhaps someone can help shed some light on.

The scenario is that a client connects and everything works fine.
If this same client reconnects a while later, not sure how long a while is but this could be days, using the same channelId it appears that when faye publishes messages, this channel is not included.
There is no real indication that anything is wrong which makes it difficult to troubleshoot.
The assumption that the channel in question is not included when faye publishes a new message is based on logging.

We have deployed faye behind a proxy and use ping to keep the connection alive but in this case there might have been a while since the last ping so I'd expect the connection to have been closed. However, when the client comes back there is both a handshake and a subscribe event where we have a new clientId but the same old channelId. I would expect that this client and channel would be re-registered but this appears not to be the case.

Has anyone else come across this issue? Any thoughts or ideas on how to handle this that doesn't involve a complete refresh to get a new channelId?

**Comment by jcoglan** [comment]
I'm not sure what you mean when you use the term 'channelId' -- that's not a field in the protocol so I'm just uncertain what you mean when you say Faye isn't including a channel when publishing, or that a channel should be "re-registered".

Can you give a more concrete example of what you've observed and what you expect to happen?

**Comment by jcoglan** [comment]
@carlnordenfelt I just wanted to check you saw my last comment. If you have any feedback on my questions, please do leave a comment here.

**Comment by carlnordenfelt** [comment]
Hi,
It's been a while since we last saw this issue so I think we either solved it or it resolved itself.
Either way I'll close the issue.
