### ISSUE TITLE
Automatic re-subscription on subscribe-error

### ISSUE THREAD

**Issue by deliminator** [faye/faye#462]
I have a custom bayeux backend that may send a "503:service unavailable" error to clients for any requests, including subscription messages. I found that this breaks the Faye browser-client's automatic resubscribe feature, because it will not retry a subscription if the subscribe fails with an explicit error (as opposed to a network failure).

I'm working around this issue by sending a success-response to the subscribe message and immediately closing the session, causing a re-handshake and re-subscribe. This works, but it seems not to be the best way to approach it.

Is there a recommended way to handle this case from the server side? I'd prefer not to require an extension/scheduler on the client to handle this scenario, since I'm not in control of all of our clients.

Alternatively, can this case be handled in the faye clients?

**Comment by jcoglan** [comment]
@deliminator Apologies for the delay on this, it's been a hectic few months. I was wondering if you could share the extension you use to do this, it might prompt ideas for how this could be baked into Faye.

**Comment by jcoglan** [comment]
@deliminator Did you see my last comment? If you're able to share some code with me that would help to make progress with this issue.

**Comment by jcoglan** [comment]
I'm going to close this issue due to lack of feedback, but I'll keep it in mind for future development as I'm working on developing a bunch of stock extensions to handle common auth workflows.
