### ISSUE TITLE
React-native api request slowness & implementation question

### ISSUE THREAD

**Issue by devbriguy** [faye/faye#463]
Hi @jcoglan. I'm currently using faye inside a react-native app. I want to make sure my implementation is done correctly. I did notice this gist:  https://gist.github.com/jsdf/7b71a590caaa6dccbd31 & closed issue #431 that also mentions it but did not implement it like that. First, the slowness occurs when I mount this component repetitively (3 or more) it seems the api requests get bottlenecked but I have server logs that say they were responded to in milliseconds. Second, do I have anything missing in the below implementation? Also, when I comment out the faye implementation it behaves normally. Api requests are also done just before faye subscribes.

```javascript
const Faye = require('faye')
var fayeClient = new Faye.Client(FAYE_URL)
// ...
componentWillMount() {
  fayeClient.subscribe(channel, function(message) {
    // process message
  }
  const logger = { 
      incoming: function(message, callback) {
        callback(message)
      },
      outgoing: function(message, callback) { 
         // these details to authenticate with server. 
        if (!message.ext) {
          message.ext = {
            userId: user_id,
            oauth_token: token
          }
        }
        if (!message.clientId) {
          message.clientId = {
            clientId: CLIENT_ID
          }
        }
        callback(message)
      }
    }
    fayeClient.addExtension(logger)
}
componentWillUnmount() {
    if (fayeClient != null) {
      fayeClient.unsubscribe(channel)
      fayeClient = null
    }
}
// ...
```

**Comment by devbriguy** [comment]
Faye client needed to be also disconnected in unmount. Multiple connections resulted in slowing down other api requests.

**Comment by razerduy** [comment]
Hi @devbriguy ,
I want to use this faye lib inside a react-native app. Can you help me?
I setup this lib inside my app but when app opening. App crash immediately.

In constructor, i put: 
this.fayeClient = new Faye.Client('ws://localhost:4002/trigger/');

In componentDidMount, i put: 
this.fayeClient.subscribe('job/700669d0-f5d0-11e6-9421-ddba1970f3c3', (mess) => {
  console.log('mess', mess);
});

In componentWillUnmount, i put:
if (this.fayeClient != null) {
   this.fayeClient.unsubscribe('job/700669d0-f5d0-11e6-9421-ddba1970f3c3');
   this.fayeClient = null;
}

**Comment by devbriguy** [comment]
Hi @razerduy Sure. Did you import faye lib inside the component? Also, you should add `fayeClient.disconnect()` to the componentWillUnmount. What error message do you get when it crashes?

**Comment by razerduy** [comment]
Hi @devbriguy ,
I imported faye lib inside the component. 
When app start, it crash. I have open debug console in chrome browser and i see a message relate faye socket. 
The message is Unbalanced calls start/end for tag 1 - the message just display when i init faye.Client in componentDidMount. If i init Faye.Client in constructor, app will crash without message.
So i have to do now?

**Comment by razerduy** [comment]
Hi @devbriguy ,
Now, i have implemented this faye lib inside my app.

**Comment by razerduy** [comment]
Hi @devbriguy ,
How to disconnect or unsubscribe channel? I called method fayeClient.unsubscribe(channel, null); or fayeClient.disconnect(); but fayeClient still receive message if server sent message.

**Comment by devbriguy** [comment]
Hi @razerduy I allocate fayeClient in `componentWillMount` and it's a variable that resides outside the class. I unsubscribe and disconnect like so: 

```javascript
componentWillUnmount() {
    if (fayeClient != null) {
      const channel = // your channel name
      fayeClient.unsubscribe(channel);
      fayeClient.disconnect()
      fayeClient = null
    }
}
```
If you are still having issues make sure the component is being unmounted.

**Comment by razerduy** [comment]
Thanks @devbriguy ,
but now i have an new issue, client always receive 2 same message. 
You used to know this issue before when implement faye inside react native?

**Comment by SubhaPrince** [comment]
Plz send me one example where i can able to subscribe any channel. I have tried but getting this error.

**My sample code...**
var faye_url = "http://xxx.com:9292/faye";
var fayeClient = new Faye.Client(faye_url);
var channel = "/xx/8237";
var token = "xxxxx";
fayeClient.setHeader("Authorization", token);

class FayeServer {
  msg = null;
  constructor() {
    const logger = {
      incoming: function(message, callback) {
        console.log(message);
        callback(message);
      }
    };
    fayeClient.addExtension(logger);
    this.msg = fayeClient.subscribe("/xx/8237", function(message) {
      alert("message");
    });
  }


**Error log...**
channel:"/meta/subscribe"
clientId:"oxxxxxasde3dgk33l43bxxxxxxx"
error:"Incorrect signature."
id:"3"
subscription:"/xxxx/8237"
successful:false


Thanks

**Comment by SubhaPrince** [comment]
@devbriguy  I followed your code but i am not understating where i am doing wrong. plz help me out this issue. I am sharing snap shot..

**Client side code..**
import Faye from "faye";
var faye_url = "http://xxx.com:9292/faye";
var token = "xxxx";
var fayeClient = new Faye.Client(faye_url);
var channel = "/conversations/8237";
var c_id;
class FayeServer {
  uid = "";
  msg = null;
  messagesRef = null;

  componentWillMount() {}
  constructor() {
    this.msg = fayeClient.subscribe(channel, function(message) {
      alert("message");
    });

    const logger = {
      incoming: function(message, callback) {
        c_id = JSON.stringify(message.clientId);
        console.log(message);
        //callback(message);
      },
      outgoing: function(message, callback) {
        if (!message.ext) {
          message.ext = {
            oauth_token: token
          };
        }
        callback(message);
      }
    };
    fayeClient.addExtension(logger);
  }
}
export default new FayeServer();


**server side** 
1. _My controller_ 
def test
    respond_to do |f|
      f.json
    end
  end

2. _View_
<% publish_to conversation_path(8237) do %>
  <% puts "DEBUG>>>>> inside test.json.erb"%>
  <%= {state: 'success'}.to_json %>
<% end %>


 I am hitting **http://xxxx.com/messages/test.json** And expecting alert **message**


Thanks

**Comment by devbriguy** [comment]
hi @SubhaPrince I'm not sure I follow your code. Are you receiving messages? What appears to be the problem? I'm seeing you are connected locally at 9292. Is your server running locally?

**Comment by SubhaPrince** [comment]
Hii @devbriguy  thanks for looking my issue. From the following code 

this.msg = fayeClient.subscribe(channel, function(message) {
alert("message");
});

1. if i do this.msg._client._state returns 3 means connected .
2. problem here is alert not showing means the block of subscription are not invoking.
