### ISSUE TITLE
sticky sessions and withCredentials

### ISSUE THREAD

**Issue by deliminator** [faye/faye#464]
We are running a custom server implementation behind a load balancer (AWS ALB) and want to use the load balancer's sticky session cookies feature to route all requests by a faye client to the same backend node.

Both, websockets and JSONP transports work without issues. The cross-origin-long-polling transport however doesn't set any cookies because the withCredentials flags isn't set on the requests.

Although the faye server's architecture is designed in a way that it doesn't need sticky session, would it be acceptable to add an option to the faye client that causes the withCredentials flag to be set so it can work with different architectures that do use sticky sessions?

**Comment by jcoglan** [comment]
Hi @deliminator I'm sorry it's taken me a few months to get to your issues, it's been a busy year. I just pushed a commit to add this functionality, should be in the next release.

https://github.com/faye/faye/commit/876f0ab5a3fce6bf1ef37e858da7b7e101ff4c71

Can you just confirm that this enables the behaviour you wanted?

**Comment by jcoglan** [comment]
As I didn't get a response to my last question, I'm closing this issue, but please do let me know if there's anything further you'd like to add.

**Comment by jcoglan** [comment]
Just letting you know that the newly-released version 1.3.0 allows cross-origin requests to set cookies and enables this in the client.
