### ISSUE TITLE
One connection to server per browser

### ISSUE THREAD

**Issue by bato3** [faye/faye#469]
Now each tab make own websocket connection. 
Is possible to share this connection between tabs? (eg.:  [Web Workers](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API), [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/Broadcast_Channel_API))
My users can open many tabs...

**Comment by jcoglan** [comment]
You can use `Faye.Client` from a WebWorker, yes. What exactly did you have in mind?

**Comment by bato3** [comment]
I'm not good with JS (and lazy) and I wanted to ask about adding this directly to the library.

**Comment by jcoglan** [comment]
It won't be added directly to the library. Starting a WebWorker requires a path to a script on your website containing the worker's code, and Faye doesn't know the URL for any worker script you might have. Even if it did know that, there's a lot of decisions about where message listeners execute -- in the worker or in the main window -- and how the main window and workers should communicate, if necessary. At this stage I think those decisions are best left to users.

BroadcastChannel does look like useful technology but it's still experimental and I'd consider it out of scope. All Faye deals with is providing a messaging connection to your server; how many of these you create and how you manage them is up to you.
