### ISSUE TITLE
How do you Prevent Echoing ?

### ISSUE THREAD

**Issue by DrakenZA** [faye/faye#471]
Im currently using Faye for a chatroom, and the users use the .publish function themselves to send messages to the 'room'.

The issue im having, is everything a user sends, is getting sent back to them.

Is there some way to stop this built in, or does anyone know a way i could build an extension that would stop sending self data back to self.

**Comment by jcoglan** [comment]
I assume this is because your client is subscribed to the same channel it's publishing messages to?

**Comment by DrakenZA** [comment]
Correct. Im using 'subs' as 'rooms'.

At the moment, im ignoring on the client side, but i want to move it server side if possible.

**Comment by jcoglan** [comment]
There isn't a way to do this on the server side. If you need this functionality, you need to implement it on the client by tagging messages with something to identify the sender and then checking this sender value in your `subscribe()` callback.

**Comment by bato3** [comment]
In "my" chat this is resolved in client. Every message have unique ID, and before display it  - client check that is it is present.

**Comment by Xsmael** [comment]
Why is echoing a problem for your chat room ? don't you have to display the message to the sender itself as well ?  i mean if i send a message, i also need to see it right?

**Comment by jcoglan** [comment]
Does anyone have any further questions about this or should I close the issue?

**Comment by jcoglan** [comment]
I'm going to close this as there were no responses to my last question. If you still need help, please leave more comments and I'll take a look :)
