### ISSUE TITLE
Anyone able to help with Updating Faye-Rails to Latest Faye ?

### ISSUE THREAD

**Issue by DrakenZA** [faye/faye#472]
https://github.com/jamesotron/faye-rails

The current dev doesnt seem to be working on it anymore, im not sure how i would go about 'upgrading' it to use the latest faye.

Could someone help me out or point me in the right direction ?

**Comment by jcoglan** [comment]
You would need to change this line to reflect the version of Faye you want to use:

https://github.com/jamesotron/faye-rails/blob/master/faye-rails.gemspec#L15

**Comment by DrakenZA** [comment]
Thank you, will give that a try !

**Comment by jcoglan** [comment]
@DrakenZA How did you get on? Should I close this issue?

**Comment by jcoglan** [comment]
I'm going to close this issue due to lack of response, and because it's out of scope -- we don't maintain faye-rails.
