### ISSUE TITLE
Issues with Faye server when behind HTTPS 

### ISSUE THREAD

**Issue by jimishjoban** [faye/faye#475]
Hello,

We had a normal Faye server setup which was working fine/perfectly with HTTP. As soon as we switched our website to HTTPS, We started to see a Lot of errors in nginx around "upstream prematurely closed connection while reading response header from upstream"

The nginx Configuration is simple:

    upstream fayeserver {
      ip_hash;
      server 127.0.0.1:9292;
      server 127.0.0.1:9293;
     server 127.0.0.1:9294;
      server 127.0.0.1:9295;
    }

      location /faye {
        proxy_set_header  X-Real-IP  $remote_addr;
        proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   X-NginX-Proxy    true;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_pass http://fayeserver;

        break;

     }

The Website has JS file which would hit https://chatty.desidime.com/faye and am assuming Faye takes care of everything else.

However, we constantly see errors like this in Nginx Logs...

`[error] 4009#0: *28900571 upstream prematurely closed connection while reading response header from upstream, client: 162.158.46.12, server: chatty.desidime.com, request: "GET /faye?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fconnect%22%2C%22clientId%22%3A%22srlq5ty30aa81yfysnksbessjwrrd89%22%2C%22connectionType%22%3A%22callback-polling%22%2C%22id%22%3A%226%22%7D%5D&jsonp=__jsonp3__ HTTP/1.1", upstream: "http://127.0.0.1:9293/faye?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fconnect%22%2C%22clientId%22%3A%22srlq5ty30aa81yfysnksbessjwrrd89%22%2C%22connectionType%22%3A%22callback-polling%22%2C%22id%22%3A%226%22%7D%5D&jsonp=__jsonp3__", host: "chatty.desidime.com", referrer: "https://www.desidime.com/posts"
2017/06/15 17:42:18 [error] 4009#0: *28900602 upstream prematurely closed connection while reading response header from upstream, client: 162.158.46.12, server: chatty.desidime.com, request: "GET /faye?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fconnect%22%2C%22clientId%22%3A%22lb50fd80d16rn59f08foui670445hms%22%2C%22connectionType%22%3A%22callback-polling%22%2C%22id%22%3A%224%22%7D%5D&jsonp=__jsonp3__ HTTP/1.1", upstream: "http://127.0.0.1:9293/faye?message=%5B%7B%22channel%22%3A%22%2Fmeta%2Fconnect%22%2C%22clientId%22%3A%22lb50fd80d16rn59f08foui670445hms%22%2C%22connectionType%22%3A%22callback-polling%22%2C%22id%22%3A%224%22%7D%5D&jsonp=__jsonp3__", host: "chatty.desidime.com", referrer: "https://www.desidime.com/forums/hot-deals-online"`

As far as SSL Termination goes, We use Cloudflare and Nodebalancer on front, so all SSL connection terminates on Nodebalancer itself, which I dont think should be a problem... Correct?

On chrome, We could sometime see a long Pending request which happens to

https://chatty.desidime.com/faye

Sometimes it quickly returns a 200 response, however sometime it waits and waits ... And we can see the Nginx logs throwing the upstream error...

Any idea on what we might be doing wrong?

**Comment by jcoglan** [comment]
Hi @jimishjoban, apologies for the delay, you caught be just before going on vacation and my backlog filled up.

I just tried connecting to the URL you gave, and it does work, even if it does feel a bit slow. Here's a response I got:

```
HTTP/1.1 200 OK
Date: Wed, 02 Aug 2017 19:22:40 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 300
Connection: keep-alive
Set-Cookie: __cfduid=d9548e4aa6afdf38948e35d89da69a3e71501701759; expires=Thu, 02-Aug-18 19:22:39 GMT; path=/; domain=.desidime.com; HttpOnly
Cache-Control: no-cache, no-store
X-Content-Type-Options: nosniff
Access-Control-Allow-Methods: GET, POST, OPTIONS, PUT, DELETE
Server: cloudflare-nginx
CF-RAY: 3883683b7f8f6a25-LHR

[{"channel":"/meta/handshake","successful":true,"version":"1.0","supportedConnectionTypes":["long-polling","cross-origin-long-polling","callback-polling","websocket","eventsource","in-process"],"clientId":"qe5dtpwdbvb77i0kzlpwby02ja0wqx9","advice":{"reconnect":"retry","interval":0,"timeout":45000}}]
```

Does that mean you got things working, or is there still a problem? Have you tried removing nginx from the equation and connecting directly to the Faye server to check that's still working fine?

**Comment by jcoglan** [comment]
As I didn't get a response to my last question I'm going to assume this is resolved and close it. However if this is still a problem, please leave more comments and I'll take a look :)
