### ISSUE TITLE
Refused to connect to wss://api.smooch.io/faye' because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy

### ISSUE THREAD

**Issue by kenyeung128** [faye/faye#477]
Refused to connect to wss://api.smooch.io/faye' because it appears in neither the connect-src directive nor the default-src directive of the Content Security Policy

Does anyone has this issue? some browsers in iphone throw this error, and can't get the message from the server.

**Comment by jcoglan** [comment]
@kenyeung128 does the client successfully make normal HTTP long-polling requests to `https://api.smooch.io/faye`? Does it continue to function in spite of the WebSocket failure, or does this stop it working completely?

**Comment by jugarrit** [comment]
@jcoglan it stops working completely.
See PR referencing this issue for details.

**Comment by jcoglan** [comment]
@kenyeung128 Can you confirm that @jugarrit's PR fixes the problem for you?

**Comment by jcoglan** [comment]
Just letting you know that the fix for this issue has finally been released in version 1.3.0.
