### ISSUE TITLE
What is "context" for handshake function in react native

### ISSUE THREAD

**Issue by SubhaPrince** [faye/faye#479]
handshake: function(callback, **context**) {}

**Comment by jcoglan** [comment]
I'm not sure how this affected by React, but `context` is the value of `this` the callback will be invoked with, on this line: https://github.com/faye/faye/blob/1a297b0e094927cde04cf0595e17a2ed4c3f1030/src/protocol/client.js#L123.

In future, would you mind asking questions on the [mailing list](https://groups.google.com/forum/#!forum/faye-users) and leave GitHub issues for reporting bugs?

**Comment by jcoglan** [comment]
Did you have any further questions, or can I close this issue?

**Comment by jcoglan** [comment]
I'm going to close this issue due to lack of responses, but please re-open it if you'd like to continue the discussion :)
