### ISSUE TITLE
ReferenceError > location is not defined

### ISSUE THREAD

**Issue by lautiamkok** [faye/faye#485]
I get this error when I use Faye with Nuxt.js:

> ReferenceError
> location is not defined

It points to this file:

```
node_modules/faye/src/util/uri.js

    consume('pathname', /^[^\?#]*/);
    consume('search',   /^\?[^#]*/);
    consume('hash',     /^#.*/);

    uri.protocol = uri.protocol || location.protocol;

    if (uri.host) {
      uri.host     = uri.host.substr(2);
      parts        = uri.host.split(':');
      uri.hostname = parts[0];
                
```

This is what I have on my Nuxt template:

```
<template>
  <section class="container">
    <img src="~assets/img/logo.png" alt="Nuxt.js Logo" class="logo" />
    <h1 class="title">
      USERS
    </h1>
    <ul class="users">
      <li v-for="(user, index) in users" :key="index" class="user">
        <nuxt-link :to="{ name: 'id', params: { id: index }}">
          {{ user.name }}
        </nuxt-link>
      </li>
    </ul>
  </section>
</template>

<script>
import axios from '~/plugins/axios'
import Faye from 'faye'

var client = new Faye.Client('/faye', {
  timeout: 20
})
client.publish('/foo', {text: 'Hi there'})

export default {
  async asyncData () {
    let { data } = await axios.get('/api/users')
    return { users: data }
  },
  head () {
    return {
      title: 'Users'
    }
  }
}
</script>
```

Any ideas why?

If I add `'http://localhost:3000` to the client path:

```
var client = new Faye.Client('http://localhost:3000/faye', {
  timeout: 20
})
```

I don't see the location error anymore. But I get this error instead:

> WebSocket connection to 'ws://localhost:3000/faye' failed: Connection closed before receiving a handshake response

Any ideas?

**Comment by jcoglan** [comment]
I don't know much about Nuxt.js, but what kind of platform are you running this code on? Is it a non-browser environment where there's no such thing as the `location` object?

**Comment by lautiamkok** [comment]
@jcoglan I am on Linux. This is the template I use from Nuxt https://github.com/nuxt-community/express-template

**Comment by lautiamkok** [comment]
This is my server setup:

```
import express from 'express'
import http from 'http'
import faye from 'faye'
import { Nuxt, Builder } from 'nuxt'

import api from './api'

const app = express()
const host = process.env.HOST || '127.0.0.1'
const port = process.env.PORT || 3000

const server = http.createServer(app)

console.log(host)
const bayeux = new faye.NodeAdapter({mount: 'http://localhost:3000/faye', timeout: 45})
bayeux.attach(server)

bayeux.getClient().subscribe('/foo', function(message) {
  console.log(message)
})

// Import API Routes
app.use('/api', api)

// Import and Set Nuxt.js options
let config = require('../nuxt.config.js')
config.dev = !(process.env.NODE_ENV === 'production')

// Init Nuxt.js
const nuxt = new Nuxt(config)

// Build only in dev mode
if (config.dev) {
  const builder = new Builder(nuxt)
  builder.build()
}

// Give nuxt middleware to express
app.use(nuxt.render)

// Listen the server
app.listen(port, host)
console.log('Server listening on ' + host + ':' + port) // eslint-disable-line no-console

```

**Comment by jcoglan** [comment]
Sorry, I didn't mean which OS are you running, I meant were is the code that's generating the error running? The template you first posted suggests your code is running in a browser or browser-like environment, which should have a `location` object.

However, I did notice this odd-looking line in your server code:

```js
const bayeux = new faye.NodeAdapter({mount: 'http://localhost:3000/faye', timeout: 45})
```

The `mount` option just takes a path, not a complete URL, so you probably want `mount: '/faye'` here.

**Comment by lautiamkok** [comment]
Yes it is running on a browser and I get the error on my browser screen. 

But in the first thread I also mentioned that I don't see the location error anymore after adding 'http://localhost:3000 to the client path:

```
var client = new Faye.Client('http://localhost:3000/faye', {
  timeout: 20
})
```
 But I get this error instead:

> WebSocket connection to 'ws://localhost:3000/faye' failed: Connection closed before receiving a handshake response

Yes I notice that `const bayeux = new faye.NodeAdapter({mount: 'http://localhost:3000/faye', timeout: 45})
` is incorrect. but I get still get the error for:

`const bayeux = new faye.NodeAdapter({mount: '/faye', timeout: 45})`

**Comment by jcoglan** [comment]
You won't get the error when calling `new Faye.Client('http://localhost:3000/faye', ...)` because the client is no longer trying to infer the scheme, host and port from the location of the current page. Does the environment where you client is running have a global `location` object? Are you able to find out what `location` refers to in `uri.js`?

**Comment by jcoglan** [comment]
What is the response if you run this in your terminal?

```
curl -siX GET http://localhost:3000/faye \
    -H 'Upgrade: WebSocket' \
    -H 'Connection: Upgrade' \
    -H 'Sec-WebSocket-Key: yxGmtT3l7gr5OjS6nsT/KQ==' \
    -H 'Sec-WebSocket-Version: 13'
```

**Comment by lautiamkok** [comment]
@jamesotron 

"Are you able to find out what location refers to in uri.js?"
 It refers to this line `uri.protocol = uri.protocol || location.protocol;`

I attached what I see on my screen when I run `http://127.0.0.1:3000/` on my browser:

<a href="http://www.freeimagehosting.net/commercial-photography/"><img src="https://i.imgur.com/We7D4ct.png" alt="commercial photography locations"></a>

**Comment by lautiamkok** [comment]
Nothing happens when I run:

```
curl -siX GET http://localhost:3000/faye \
    -H 'Upgrade: WebSocket' \
    -H 'Connection: Upgrade' \
    -H 'Sec-WebSocket-Key: yxGmtT3l7gr5OjS6nsT/KQ==' \
    -H 'Sec-WebSocket-Version: 13'
```

**Comment by lautiamkok** [comment]
> "Does the environment where you client is running have a global location object?"

I don't know. But I think it does not have not. What can we do if it does not?

**Comment by lautiamkok** [comment]
I tested it with:

```
var x = location.origin
console.log(x)
```

And I get the same location error. So I guess it does not have that.

**Comment by jcoglan** [comment]
> "Are you able to find out what location refers to in uri.js?"
> It refers to this line uri.protocol = uri.protocol || location.protocol;

I meant, at that point in the code, what does the variable name `location` point at? It's supposed to point at the global `location` object, but if the code has been enclosed in a function that defines a local variable with the same name, it will refer to that instead.

Which browser are you running? It looks like Chrome from the user agent string. How did you determine that there's no `location` object? Where did you run the code in your last comment? What is displayed if you just type the word `location` into the dev tools console? What about the expression `window.location`?

**Comment by lautiamkok** [comment]
I think this might be answer https://github.com/nuxt/nuxt.js/issues/30

Nuxt is a server side framework, while `new Faye.Client` is supposed to be on the client side.

**Comment by lautiamkok** [comment]
> What about the expression window.location?

I will get the same error because `window.location` is a client code. Nuxt is running on the server.

**Comment by jcoglan** [comment]
I didn't realise your initial example ran on the server rather than in the browser. `Faye.Client` does work on the server but you need to pass a complete URL. In the browser, you can use partial URLs just as you can for `href` and `src` attributes.

**Comment by lautiamkok** [comment]
That means we cannot use `new Faye.Client` in Nuxt template directly.

**Comment by lautiamkok** [comment]
> Faye.Client does work on the server but you need to pass a complete URL. In the browser, you can use partial URLs just as you can for href and src attributes.

Yes I tested that without Nuxt and it works fine. :-D

**Comment by lautiamkok** [comment]
Strange though I can use socket.io directly in the Nuxt template. So I thought it would be the same for Faye.

**Comment by lautiamkok** [comment]
this is the reason why I have the location error - https://nuxtjs.org/faq/window-document-undefined/

**Comment by jcoglan** [comment]
Does that mean I can close this issue?

**Comment by lautiamkok** [comment]
Yes I am closing it. Cheers.

**Comment by doubleminus** [comment]
Having the same problem here and am wondering...what was the fix?

**Comment by pcj** [comment]
I'm seeing same issue.  On my end, there is no error if the string `http://localhost:8000/faye` is used, but no connection occurs (browser client _are_ able to connect to this endpoint).  If any other string like `//localhost:8000/faye` or `/faye` is provided, the `ReferenceError` is thrown.

> ### Server-side Node.js clients

> You can use Faye clients on the server side to send messages to in-browser clients or to other server-side processes. The API is identical to the browser client.

> To create a client, just supply the host you want to connect to:

> `var client = new faye.Client('http://localhost:8000/faye');`
> You can then use `client.subscribe()` and `client.publish()` to send messages to other clients; see the > browser client documentation for more information.

https://faye.jcoglan.com/node/clients.html

```
c:\...\node_modules\faye\src\util\uri.js:36
    uri.protocol = uri.protocol || location.protocol;

ReferenceError: location is not defined
    at Object.parse (C:\...\node_modules\faye\src\util\uri.js:36:36)
    at klass.initialize (C:\...\node_modules\faye\src\protocol\dispatcher.js:21:28)
    at new klass (C:\...\node_modules\faye\src\util\class.js:13:28)
    at Function.Dispatcher.create (C:\src...\node_modules\faye\src\protocol\dispatcher.js:179:10)
    at klass.initialize (C:\...\node_modules\faye\src\protocol\client.js:44:35)
    at new klass (C:\...\node_modules\faye\src\util\class.js:13:28)
```

**Comment by jcoglan** [comment]
@pcj Relative URLs are not supported on Node. In the browser, they are interpreted relative to the current page URL as expressed by the `location` object (just like other URLs like `href` and `src` attributes), but on Node there is no 'current page' to resolve URLs relative to.

**Comment by houssembenjemia** [comment]
i have the same problem ..what  is was the fix,
