### ISSUE TITLE
CSRF protection and Rails Scaling

### ISSUE THREAD

**Issue by DrakenZA** [faye/faye#486]
From the documentation, its stated in the rails CSRF protection example, that you must use Faye as middleware, so it can access the session and do the confirming.

"This extension needs to access the Rails session, and to allow this you must put Faye at a specific place in the Rails middleware stack. In your application config, add Faye::RackAdapter after your app’s session store middleware, adding CsrfProtection as an extension." - https://faye.jcoglan.com/security/csrf.html

The issue i run into, is ive been looking into the scaling aspects of my app now, and ive read around that in order to scale faye with redis, you going to have to NOT use Faye in middleware, and rather have it as its own process(dyno for heroku).

So now im a bit stuck. Is there no way to have CSRF protection along with Faye using Redis ?

**Comment by jcoglan** [comment]
> The issue i run into, is ive been looking into the scaling aspects of my app now, and ive read around that in order to scale faye with redis, you going to have to NOT use Faye in middleware, and rather have it as its own process(dyno for heroku).

I'm not sure where you read this but it's not strictly true. It is certainly simpler to manage the scaling requirements of Faye and your web app if they're separate systems, but technically you can run Faye backed with Redis as part of your Rails middleware. I just don't *recommend* that people doing serious deployments take that approach.

**Comment by jcoglan** [comment]
I'd also recommend that if this gets too complex, you back away from cookies as an auth mechanism; they don't work well with long-lived connections or the semantics of the Bayeux protocol. You're better off doing authentication within the protocol itself, as the other security articles on the site describe.

Besides, if you deploy Faye as a separate service, you'll probably put it under a different hostname to your main app, so you won't be receiving your app's cookies with Faye connections.

**Comment by DrakenZA** [comment]
Ahh thanks for the info !
