### ISSUE TITLE
Occasional "can't add a new key into hash during iteration"

### ISSUE THREAD

**Issue by tspacek** [faye/faye#489]
We get occasional `can't add a new key into hash during iteration` exceptions when sending.

We are running one Faye::Client in a connection pool (https://github.com/mperham/connection_pool) between 10 Sidekiq workers. So it could be due to this concurrency.

The stack trace is:

```
RuntimeError: can't add a new key into hash during iteration
  from set.rb:331:in `add'
  from faye/transport/web_socket.rb:44:in `block in request'
  from faye/transport/web_socket.rb:44:in `each'
  from faye/transport/web_socket.rb:44:in `request'
  from faye/transport/transport.rb:44:in `send_message'
  from faye/protocol/dispatcher.rb:121:in `send_envelope'
  from faye/protocol/dispatcher.rb:100:in `send_message'
  from faye/protocol/client.rb:295:in `block in send_message'
  from faye/protocol/extensible.rb:30:in `block in pipe_through_extensions'
  from app/services/socket_service_auth.rb:5:in `outgoing'
  from faye/protocol/extensible.rb:38:in `block in pipe_through_extensions'
  from faye/protocol/extensible.rb:41:in `pipe_through_extensions'
  from faye/protocol/client.rb:292:in `send_message'
  from faye/protocol/client.rb:267:in `block in publish'
  from em/deferrable.rb:151:in `set_deferred_status'
  from faye/mixins/deferrable.rb:10:in `set_deferred_status'
  from faye/protocol/client.rb:119:in `connect'
  from faye/protocol/client.rb:264:in `publish'
  from app/services/publisher.rb:104:in `block in publish_faye'
  from connection_pool.rb:64:in `block (2 levels) in with'
```

So it seems to be this:
```
    def request(messages)
      @pending ||= Set.new
      messages.each { |message| @pending.add(message) }
```

And the only spot I can see which could be iterating `@pending` is 
`next unless message = @pending.find { |m| m['id'] == reply['id'] }` in `web_socket#connect`

So it's related to sending messages while receiving replies?

**Comment by tspacek** [comment]
🤔  Could it be that the thread I sent on with 

```
    Publisher::FAYE_POOL.with do |faye|
      faye.publish(channel.to_s, data)
    end
```

Is different to the thread that `socket.onmessage` is called on with replies?

**Comment by jcoglan** [comment]
All interaction with the client should happen on the EventMachine thread. If you use the same client from multiple threads you will almost certain get problems like this.

**Comment by tspacek** [comment]
That was it. It turns out that calling it from `EM.schedule { faye.publish(channel.to_s, data) }` has resolved the issue. Thank you for your time!
