### ISSUE TITLE
'Local' Publish and Subscribe

### ISSUE THREAD

**Issue by letsgotomars** [faye/faye#495]
According to the documentation "Clients do not send each other messages directly, instead they send their messages to channels, and the server figures out which clients need to receive the message." For our application this is the desired behavior in most cases where published channels from clients should be passed to a server to be distributed to other potential clients. However we would like the ability to augment these 'global' channels (using 'global' to mean channels which are passed to the server and can be subscribed to by multiple clients) with 'local' channels (using 'local' to mean channels which are only published and subscribed to in the local browser window/tab instance and do not go to the server)

Is this possible or would you consider it as a feature request? What are your thoughts? We have instances where we want to create some 'local' channels which are composed of computations of various 'global' channels, but don't want to necessarily make them available 'globally' or waste server resources. Ideally Whether a channel is 'global' or 'local' would be transparent in the subscribe process, and there would be some mechanism to publish 'locally'.

By the way we love your library and use it extensively.

**Comment by letsgotomars** [comment]
@jcoglan what are your thoughts? Is this outside the scope of what you intend to use Faye for? If not a wrapper library might be a more appropriate solution.

**Comment by jcoglan** [comment]
Sorry for my slow reply. I think this is out of scope for Faye; if you want local pub/sub functionality there are much simpler ways of achieving that without using this library.

It's also a very different problem space from doing this over the network. For example, you might want messaging between objects in the same runtime, or messaging between workers, or between different instances of your app running in tabs in the same browser. All these require different implementations, and I wouldn't consider any of that to be within the scope of Faye. It would be entirely possible to implement what you need and then abstract over both that and Faye, if that helps.

**Comment by letsgotomars** [comment]
No worries on the late response I figured this was probably out of scope. We were able to easily implement a wrapper around Faye that addressed this use-case.
