### ISSUE TITLE
Faye Nodeadapter not working when hosted in heroku

### ISSUE THREAD

**Issue by vbalas** [faye/faye#496]
We are evaluating the Faye for our realtime dashboard page. Client is React app and server is a node app. It works fine locally. When these were deployed to heroku, the communication isn't working.

**Comment by jcoglan** [comment]
I don't why your specific app doesn't work on Heroku, but Faye on Node certainly works there. Here's a demo app I just created to try this out:

https://faye-demo.herokuapp.com/

Source code:

```js
// app.js

const faye = require('faye'),
      fs   = require('fs'),
      http = require('http'),
      path = require('path');

let server = http.createServer((req, res) => {
  let file = fs.createReadStream(path.join(__dirname, 'index.html'));
  file.pipe(res);
});

let bayeux = new faye.NodeAdapter({ mount: '/faye' });
bayeux.attach(server);

server.listen(process.env.PORT);
```

```html
<!-- index.html -->

<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Faye Heroku demo</title>
    <script src="/faye/client.js"></script>
  </head>
  <body>

    <h1>Faye Heroku demo</h1>

    <script>
      Faye.logger = console;
      var client = new Faye.Client('/faye');

      client.subscribe('/msg', msg => {
        console.log(msg);
      });
    </script>

  </body>
</html>
```

If you send data to this app, it shows up in the browser console:

    curl -X POST https://faye-demo.herokuapp.com/faye -H 'Content-Type: application/json' -d '{"channel": "/msg", "data": {"hello": "world"}}'

**Comment by vbalas** [comment]
Thanks. Receiving a Bad request response. We are behind corporate proxy. So not sure how to get past this.

**Comment by jcoglan** [comment]
Sorry, I'm not sure what you mean. What is your proxy blocking access to?

**Comment by jcoglan** [comment]
@vbalas Hi, is this an ongoing issue for you, or can I close this issue?

**Comment by jcoglan** [comment]
I'm going to close this issue due to lack of responses, but please re-open it if you'd like to continue the discussion :)
