### ISSUE TITLE
Microsoft Edge WebSocket Error: SECURITY_ERR, Cross zone connection not allowed

### ISSUE THREAD

**Issue by slprogrp** [faye/faye#498]
Hi there,

Thanks for a great product in Faye!

I have a faye client running in a web page hosted on a remote server.  I open a browser on my local machine, and load that page in from the remote server.  The faye client connects to a locally installed node application running a fay server on http://localhost:[PORT]/faye when the page is loaded.  This worked fine when I first built it.  It worked fine in both Microsoft Edge and Chrome, but now no longer works in Edge.

Instead I get the following error message:

> SCRIPT12017: SCRIPT12017: WebSocket Error: SECURITY_ERR, Cross zone connection not allowed

I did a bit of research on this and saw some posts on SO suggesting to:

> In the Microsoft Edge browser type "About:flags" in the title bar (search bar). No quotes, Tick/Un-tick the "allow Localhost Loopback" feature.

Which I did but it made no difference.

Is this a known issue that is being resolved, or is there a work around for this?

**Comment by jcoglan** [comment]
Hi @slprogrp, sorry for my slow reply. Since 1.2.4, the following commit has gone in to catch content security policy restrictions and recover from them, falling back to regular HTTP if `WebSocket` throws an error:

https://github.com/faye/faye/commit/0263dce4da30f664367145056055d95c7de2dec1

Are you able to let us know if this fixes the problem you're seeing?

**Comment by Munavvarhusen** [comment]
Here are 2 changes that helped me fix the issue and establish a localhost WebSocket connection.

 1. In the Control Panel - Internet Option, select the Security Tab. In the Security tab, select Local intranet zone. Click on Sites button and uncheck all checkboxes in Local intranet dialog. OR
 2. In the Control Panel - Internet Option, select the Security Tab. In the Security tab, select Local intranet zone. Click on Sites button and then on Advanced button in the Local intranet dialog, add the required web address to the same zone as localhost.

**Comment by jcoglan** [comment]
@slprogrp Can you confirm whether the above commit fixes this issue? I'd like to cut a release and will have to close this issue if I don't get a confirmation soon.

**Comment by slprogrp** [comment]
I think given that Edge has moved to Chrome engine, the issue no longer happens and so is as good as solved.
Thanks for following up ;-)
