### ISSUE TITLE
How to unsubscribe a client from the server?

### ISSUE THREAD

**Issue by codeowl1** [faye/faye#501]
Hi there,

I have token based authentication in place, and I have an expiry on tokens.  If a token expires the user should no longer receive messages on channels they are subscribed to.  Is there a way from the server, to unsubscribe clients from channels so they no longer receive messages, when I detect an expired token?

Thanks for your time.

**Comment by jcoglan** [comment]
This is possible using a server-side extension. As well as the `/meta/subscribe` channel that clients use to register new subscriptions, there's the `/meta/connect` channel that they use to poll for messages -- even if using WebSocket, clients must send this message periodically to keep its session alive.

You can put an authorisation check on this channel by adding an extension on the server side -- the `isValid()` function here would contain your logic to check the token, and returns `true` only if it's still valid.

```js
server.addExtension({
  incoming(message, callback) {
    if (message.channel === '/meta/connect') {
      let { ext: { token } = {} } = message;
      if (!isValid(token)) message.error = 'invalid auth token';
    }
    callback(message);
  }
});
```

If you assign `error` to the message here, the Faye server will not process this request and this will cause the client's session to eventually time out. It will send the following response back to the client, which should cause it to perform a new handshake -- you can use this event to request a new token, however you're doing that.

```json
  {
    "channel": "/meta/connect",
    "error": "invalid auth token",
    "successful": false,
    "advice": {
      "reconnect": "handshake"
    }
  }
```

Does that answer your question? I'm happy to provide more detail if any of this is unclear.

**Comment by jcoglan** [comment]
Does the above message answer your question, @codeowl1 ? Can I close this issue?

**Comment by codeowl1** [comment]
Yes that is perfect thanks, much appreciated.
