### ISSUE TITLE
Suppress exceptions

### ISSUE THREAD

**Issue by Neso** [faye/faye#504]
Is it possible to have option on initialisation to suppress exceptions from Faye.

**Comment by jcoglan** [comment]
Hi @Neso, sorry for my slow reply. Can you provide more detail about the exceptions you're seeing and why you need to suppress them?

**Comment by Neso** [comment]
Hi @jcoglan I will post stack trace, the main reason I would like them suppressed is because occasionally they are flaring in our error dashboards.

**Comment by Neso** [comment]
> (Type Error) Cannot read property 'sendMessage' of undefined 

And this was not coming from our local codebase, and stack traces were pointing to faye library.

**Comment by jcoglan** [comment]
This sounds like an actual bug that we should investigate, rather than silence the error. Do you have any more context, or a complete stack trace for the error?

**Comment by Neso** [comment]
I have investigated and haven't identified any adverse behaviours to the best of my expectations it is happens and then lib recovers the call. And it would appear that all messages eventually get trough. Also worth noting is that we have never noticed this in dev or qa environments but only got it reported to new relic from select number of users.

**Comment by jcoglan** [comment]
Nevertheless, it should never be the case that the client is attempting to call this method on a null reference, so if you have any further info do send it our way :)

**Comment by Neso** [comment]
Sorry that's the best I can offer. As this was logged in new relic and I don't have any more info to offer.

**Comment by jcoglan** [comment]
I'm going to close this, since absent any more information on the source of this exception we can't really do much about it. In any case, I don't believe suppressing exceptions is the right thing to do, especially not in libraries, plus in order to suppress an exception we'd need to know where it was coming from. I'm sorry I can't take this any further.
