### ISSUE TITLE
How to optimize faye back into a single minified file, now that it uses RequireJS?

### ISSUE THREAD

**Issue by codeowl1** [faye/faye#505]
Hi there,

I see Faye now uses RequireJS.  I want to minify it down to a single file so it is only a single http request to use it in the browser.  I have attempted to do this using RequireJS optimizer but have not been successful.
My attempt is documented [here](https://stackoverflow.com/questions/52125858/using-requirejs-with-node-to-optimize-creating-single-output-file-does-not-inclu).

How can I minify it back to a single file like it used to be?

**Comment by jcoglan** [comment]
Releases of Faye still include a copy of the client as a single file, that will run in the browser without further compilation. If you want to compile it yourself from source, you need to run these commands in the repository root:

```
npm install
make
```

The resulting files should end up in the `build/client` directory.

**Comment by jcoglan** [comment]
Is this an ongoing issue, or can I close it, @codeowl1 ?

**Comment by codeowl1** [comment]
Yes that solved the issue, thanks very much.
