### ISSUE TITLE
Question - ruby client

### ISSUE THREAD

**Issue by samoliuk** [faye/faye#510]
Hello,

I'm trying to add faye to my app, the rails app is supposed to only publish a lot of messages.

How can I initialize a faye client once, outside the Event Machine, and publish with it when needed? Do something like

faye_initializer.rb
```
FayeClient = Faye::Client.new('http://localhost:9292/faye')
```

some class in app
```
EM.run {
  publication = FayeClient.publish('/my_channel', 'my_message')
  publication.callback do
    log("success")
    EM.stop
  end

  publication.errback do |e|
    log("error: #{e.message}")
    EM.stop
  end
}
```

I tried to do something like that, but it publishes message only one time.
Do I have to define a new Faye::Client instance inside EM.run block for every published message?

**Comment by mgsococo** [comment]
See the bottom of https://faye.jcoglan.com/security/push.html 

You do not need to create a full Faye client to simply publish, you can do it with simple HTTP requests with the correct information.

**Comment by samoliuk** [comment]
Thanks for the confirmation @mgsococo, simple HTTP requests are what I ended up with.
