### ISSUE TITLE
Wrong versions breaks old package installations

### ISSUE THREAD

**Issue by remoe** [faye/faye#511]
Faye has non restrictive versions in package.json:

https://github.com/faye/faye/blob/master/package.json#L16

This prevent to install old installations. The latest "tough-cookie" doesn't work with Node 0.12. No, I don't want to update nodejs :)

**Comment by jcoglan** [comment]
I keep the version ranges of my dependencies open as it means end users can get updates for my dependencies without me having to publish a new package. If you need a specific version of tough-cookie, you can specify that in your own `package.json`, for example:

```json
  "dependencies": {
    "faye": "*",
    "tough-cookie": "< 3.0"
  }
```

This will install a version earlier than 3.0 into your project and will link `faye` to that version.

**Comment by remoe** [comment]
Thanks!
