### ISSUE TITLE
Logging is missing in documentation

### ISSUE THREAD

**Issue by viktomas** [faye/faye#512]
Adding logger to the Faye library is not documented. People have had issues in the past to add logger #418 and I had the issue myself. The only reference to the logger setup is in [examples](https://github.com/faye/faye/blob/master/examples/public/index.html#L44) which doesn't seem enough to me.

I'm happy to add the documentation myself if maintainer can point me to appropriate page/position in documentation.

**Comment by jcoglan** [comment]
Hi @viktomas, thanks for offering to improve our docs :)

To work on the docs, clone the repository and run the following commands:

```
bundle install
bundle exec staticmatic preview site
```

The site will then be visible at `localhost:3000`. The source code for the site is in the `site` directory -- you'll probably want to edit something inside `site/src/pages`, which reflects the page structure of the site.

**Comment by jcoglan** [comment]
@viktomas Hi, were you able to make any progress on this? Is there anything else I can help with?
