### ISSUE TITLE
Example Client and Server don't connect over https

### ISSUE THREAD

**Issue by laeeqkhan01** [faye/faye#514]
I am trying to run example faye client and server in faye/example/node.
They work beautifully on HTTP, but when I run it on HTTPS client reports  [CONNECTION DOWN]

node   server.js   4000  tls
Listening on 4000 (https)
[  SUBSCRIBE] if2wit9ixsd8zxfrfb2xk30nqjl7xuw -> /chat/*

node  client.js  4000  bayeux   tls
Connecting to https://localhost:4000/bayeux
[CONNECTION DOWN]

Could I be doing anything wrong.

**Comment by jcoglan** [comment]
Hi @laeeqkhan01, it's possible this was failing due to the SSL certificates in the repository being out of date. I have just pushed new ones to `master` so this should now work. Could you please check and confirm for me?

**Comment by jcoglan** [comment]
Hi @laeeqkhan01, I've not had any response to this and I believe updating the SSL certificates has fixed this problem, so I'm going to close this issue. Do please re-open it if it requires further attention.
