### ISSUE TITLE
Channel max length

### ISSUE THREAD

**Issue by Xsmael** [faye/faye#516]
Hello,

What is the maximum length for any channel string ?
And can we extend it ?

**Comment by jcoglan** [comment]
There's no built-in restriction on channel name length, I don't think. Are you observing something that suggests there is a limit?

**Comment by Xsmael** [comment]
> Are you observing something that suggests there is a limit?
Not really, but at the time i was asking the question i had a challenging problem that could easily be addressed using faye, but would make dynamic very long channel names...
