### ISSUE TITLE
Does faye have reserved channels ?  like "/service" for example

### ISSUE THREAD

**Issue by Xsmael** [faye/faye#518]
Hi,
I spent a huge time before getting around a strange behaviour.
In my faye server i am logging subs and unsubs

but when i subscribe to channel '/service/*' there is no mention of that in logs and i dont receive data published on that channel. but if i change it to something like '/serviiiiice/*' or any other thing, it works.
This is the first time i encounter this, so i wanted to post it here.

**Comment by jcoglan** [comment]
Hi there, yes, the channel namespace `/service/**` (as well as the `/meta/**` namespace) is reserved and clients are not allowed to subscribe to those channels. This is a requirement of the [Bayeux protocol](https://docs.cometd.org/current/reference/#_concepts_bayeux_protocol).

**Comment by Xsmael** [comment]
Oh, then it all makes sense now. Not knowing that made me go crazy and waste couple hours, thanks for the second one which I also didn't know.
