### ISSUE TITLE
failed: Cannot find module './extend'

### ISSUE THREAD

**Issue by msrivastav13** [faye/faye#521]
I have a vscode extension that depends on this module.

Since 1.30 release i get this when my compile fail and it traces back to this module

`Activating extension 'MohithShrivastava.dx-code-companion' failed: Cannot find module './extend`

Require stack:
- /Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/faye/src/util/class.js
- /Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/faye/src/protocol/client.js
- /Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/faye/src/faye_node.js
- /Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/jsforce/lib/api/streaming.js
- /Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/jsforce/lib/api/index.js
- /Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/jsforce/lib/jsforce.js
- /Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/jsforce/index.js
- /Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/@salesforce/core/lib/authInfo.js
- /Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/@salesforce/core/lib/exported.js
- /Users/mohith/Desktop/CodeCompanion/dx-code-companion/out/services/config.js
- /Users/mohith/Desktop/CodeCompanion/dx-code-companion/out/extension.js
- /Users/mohith/Desktop/Visual Studio Code.app/Contents/Resources/app/out/vs/loader.js
- /Users/mohith/Desktop/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-amd.js
- /Users/mohith/Desktop/Visual Studio Code.app/Contents/Resources/app/out/bootstrap-fork.js`

I have no idea but clearly with 1.25 it was fine so something broke when this was upgraded to latest.

**Comment by jcoglan** [comment]
Can you paste the contents of `/Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/faye/src/util/class.js` and the output of `tree /Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/faye/src`, and check what version is declared in `/Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/faye/package.json`?

**Comment by msrivastav13** [comment]
`'use strict';

var assign = require('./assign');

module.exports = function(parent, methods) {
  if (typeof parent !== 'function') {
    methods = parent;
    parent  = Object;
  }

  var klass = function() {
    if (!this.initialize) return this;
    return this.initialize.apply(this, arguments) || this;
  };

  var bridge = function() {};
  bridge.prototype = parent.prototype;

  klass.prototype = new bridge();
  assign(klass.prototype, methods);

  return klass;
};`

Here is what it has in /Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/faye/src/util/class.js

Here 

/Users/mohith/Desktop/CodeCompanion/dx-code-companion/node_modules/faye/package.json

It is `1.3.0` everywhere

**Comment by jcoglan** [comment]
So the source code on disk has `require('./assign')`, which doesn't correspond to the error you're seeing. Are you running anything that might have cached the old version in memory, for example a Webpack build process?

**Comment by msrivastav13** [comment]
May be this was cache! Thanks for help and response
