### ISSUE TITLE
Faye requesting an insecure script <URL>

### ISSUE THREAD

**Issue by imi56** [faye/faye#526]
I'm was exploring `faye` to implement `websocket` feature but got stuck due to following issue.
**The page at <URL> was loaded over HTTPS, but requested an insecure script [http://xyz/faye?message=[{"channel":"/meta/handshake","version":"1.0","supportedConnectionTypes":["websocket","eventsource","long-polling","cross-origin-long-polling","callback-polling"],"id":"1"}]&jsonp=__jsonp1](). This request has been blocked; the content must be served over HTTPS**
Config details

- rails( 4.2.11)
- faye (1.3.0)
- puma (4.3.1)

Everything fine locally since everything running over **HTTP**.
On staging, we are getting the above issue. Not sure what are we doing wrong. Points to note are:

- Puma is running using --ssl.
- **https://xyz/faye.js** renders the client JS (Note the **https**)
- Ran faye server using `rackup faye.ru -s thin -E production`
- nginx config below
```
server {
  listen 80;
  root /var/app/current;
  location / {
    proxy_pass http://mlp;
    proxy_set_header Host $host;
    rewrite /favicon.ico /public/favicon.ico;
  }

  location /faye {
    proxy_set_header Host $host;
    proxy_pass http://localhost:9292;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection 'upgrade';  
  }
}
```

**Comment by jcoglan** [comment]
What's the code you're using to start the connection to the Faye server?
