### ISSUE TITLE
Using cookiejar2 fork?

### ISSUE THREAD

**Issue by dorianmariefr** [faye/faye#537]
Hi, I made a fork to fix warnings, what do you think of adding it as a dependency?

https://rubygems.org/gems/cookiejar2

https://github.com/dorianmariefr/cookiejar2

See https://github.com/dwaite/cookiejar/pulls

And https://github.com/dwaite/cookiejar/commit/5f85661eb661673460e7ad1a04a98111566e2537 that was not released

See https://github.com/igrigorik/em-http-request/issues/354 for the other dependency that depends on cookiejar in rails

**Comment by jcoglan** [comment]
What does this change compared to `cookiejar` and how does it affect the `faye` package?

**Comment by dorianmariefr** [comment]
It's mainly the warning that it's fixed for now but I could merge the open pull request, would need to review them. Including one for having cookies apply to subdomains of subdomains

**Comment by dorianmariefr** [comment]
I got the ownership of cookiejar and there was a release, so all is good

**Comment by Nakilon** [comment]
> I got the ownership of cookiejar and there was a release, so all is good

Where is the repo? The link in your gemspec seems to be dead.

**Comment by dorianmariecom** [comment]
cookiejar is the new cookiejar2

**Comment by Nakilon** [comment]
> cookiejar is the new cookiejar2

https://github.com/dwaite/cookiejar is archived.

**Comment by dorianmariecom** [comment]
Yes I need to open a new one at dorianmariecom/cookiejar will do
